cmpsr/composer

packages/components/src/components/primitives/form/RadioButton/RadioButton.css
packages/components/src/components/primitives/form/RadioButton/RadioButton.tsx
packages/components/src/styles/index.css
packages/components/src/styles/plugins.js
packages/components/src/styles/theme.js
packages/components/src/utils/getRadioButtonClasses/index.ts

Add missing files

---

packages/components/lib/components/primitives/form/RadioButton/RadioButton.css
packages/components/lib/components/primitives/form/RadioButton/RadioButton.js
packages/components/lib/styles/index.css
packages/components/lib/styles/plugins.js
packages/components/lib/styles/theme.js
packages/components/lib/utils/getRadioButtonClasses/index.js

Add compiled files

---

.github/workflows/publish.yml

Adds Publish workflow

---

.github/workflows/publish.yml

Adds Publish workflow (#4)

---

packages/contentful/README.md

Adds Contentful Readme

---

.changeset/late-plants-do.md
packages/contentful/README.md

Testing bot + pr flow

---

.changeset/friendly-days-cheer.md
packages/contentful/README.md

Updated Contentful README

---

.github/workflows/publish.yml

Add build step to workflow

---

README.md

Doesn't work well, keeping snyk (for now) but removing the badge.
**Checklist**

Removes Known Vulnerabilities badge

---

.changeset/small-peas-exist.md
packages/components/src/components/primitives/form/CurrencyField/CurrencyField.stories.tsx
packages/components/src/components/primitives/form/CurrencyField/CurrencyField.test.tsx
packages/components/src/components/primitives/form/CurrencyField/CurrencyField.tsx
packages/components/src/components/primitives/form/CurrencyFieldIcon/CurrencyFieldIcon.test.tsx
packages/components/src/components/primitives/form/CurrencyFieldIcon/CurrencyFieldIcon.tsx
packages/components/src/components/primitives/form/CurrencyFieldIcon/stories/CurrencyFieldIcon.stories.tsx
packages/components/src/components/primitives/form/TextField/TextField.stories.tsx
packages/components/src/components/primitives/form/TextField/TextField.test.tsx
packages/components/src/components/primitives/form/TextField/TextField.tsx

**Checklist**
**What is the ticket / issue associated with this change?** (https://trello.com/c/pIdX7kME/43-borrower-flow-fixes-from-demo-june-19)

Add InputMode

---

.github/workflows/publish.yml
package.json

Move publish build step to publish-ci script

---

.changeset/rude-buckets-remember.md
packages/contentful/README.md

Removed unnecessary copy from Contentful readme

---

.changeset/gorgeous-steaks-smell.md

Dummy changeset

---

.github/workflows/chromatic.yml

Run Chromatic on changes to "packages/components"

---

.github/workflows/delete_storybook.yml

Adds exclusion for changeset branch name - COM-7

---

README.md

Adds Storybook Badge to README - COM-6

---

.changeset/swift-windows-arrive.md
package.json

Bump contentful-core version

---

.changeset/selfish-turkeys-sneeze.md
CODEOWNERS

Mainly, just so I can track usage via: https://www.pkgstats.com/@ryanhefner

Chore: Add myself to CODEOWNERS list (@ryanhefner)

---

.changeset/calm-numbers-allow.md
packages/contentful-core/src/components/ComponentRenderer.test.tsx
packages/contentful-core/src/components/ComponentRenderer.tsx

**Checklist**
Will allow for inline/local overrides/extension to `ContentfulProvider`/`componentMap` mappings.

Feature: ComponentRenderer  componentMap overrides

---

packages/analytics/README.md

add readme for analytics package

---

.changeset/cuddly-rules-join.md
packages/cloud-kms/src/Kms.test.ts
packages/cloud-kms/src/Kms.ts
packages/cloud-kms/src/index.test.ts
packages/cloud-kms/src/index.ts
packages/cloud-kms/src/types/index.ts

Add auth google cloud kms integration

---

.github/workflows/publish.yml

**Checklist**
Fix for this warning

Use appropriate main branch for actions/checkout

---

.github/workflows/publish.yml

Set main as main branch for node-setup action

---

.changeset/strange-guests-watch.md
packages/analytics/lib/integrations/segment/Segment.js
packages/analytics/src/integrations/segment/Segment.ts

Call identify on analytics object

---

.changeset/moody-papayas-tease.md
packages/contentful-core/src/components/ComponentRenderer/ComponentRenderer.tsx

Bug missing rest

---

.changeset/twelve-tomatoes-smell.md
packages/components/lib/components/primitives/form/CurrencyField/CurrencyField.js
packages/components/lib/components/primitives/form/CurrencyFieldIcon/CurrencyFieldIcon.js
packages/components/lib/utils/getDropdownSingleSelectClasses/index.d.ts.map
packages/components/lib/utils/getDropdownSingleSelectClasses/index.js
packages/components/lib/utils/getTextFieldStateClasses/index.d.ts.map
packages/components/lib/utils/getTextFieldStateClasses/index.js
packages/components/src/components/layouts/forms/Login/__snapshots__/Login.test.tsx.snap
packages/components/src/components/primitives/form/CurrencyField/CurrencyField.tsx
packages/components/src/components/primitives/form/CurrencyFieldIcon/CurrencyFieldIcon.tsx
packages/components/src/components/primitives/form/DropdownField/DropdownDownshiftSelect/DropdownDownshiftSelect.test.tsx
packages/components/src/components/primitives/form/DropdownField/DropdownNativeSelect/DropdownNativeSelect.test.tsx
packages/components/src/utils/getDropdownSingleSelectClasses/index.ts
packages/components/src/utils/getMessageClasses/index.test.ts
packages/components/src/utils/getTextFieldStateClasses/index.test.ts
packages/components/src/utils/getTextFieldStateClasses/index.ts

**Checklist**
- Renamed messages enums
- Fixed border for TextFields/CurrencyFields/Dropdowns

Style Guide Colors - Fix Borders

---

.changeset/dry-students-refuse.md
packages/contentful-core/src/components/ComponentRenderer/ComponentRenderer.tsx
packages/contentful-core/src/components/ComponentRendererWithQuery/ComponentRendererWithQuery.tsx

Adds try.catch to prevent a page completely falling over.

Adds try catch to contentful-core

---

.changeset/spotty-games-invent.md
packages/contentful-core/src/components/ComponentRendererWithQuery/ComponentRendererWithQuery.tsx

Adds null return when null (loading) data

---

.changeset/smart-planes-worry.md
packages/contentful-core/README.md
packages/contentful-core/src/components/ComponentRendererWithContext/ComponentRendererWithContext.tsx
packages/contentful-core/src/components/ComponentRendererWithQuery/ComponentRendererWithQuery.tsx
packages/contentful-core/src/context/ContentfulContext.ts
packages/contentful-core/src/context/ContentfulProvider.tsx

**Checklist**
* Added to support `preview` in the `x-content` repo

Feature: Contentful Preview

---

.changeset/chilly-cows-relax.md
packages/firestore/src/db/FirestoreDb.test.ts
packages/firestore/src/db/FirestoreDb.ts

Check for undefined value

---

.changeset/happy-bees-fry.md
packages/contentful-core/.babelrc

**Checklist**
https://app.asana.com/0/1192025116616449/1195811919401313/f
- We are adding support for IE11 in x-content and this is the only dependency that is not compatible.

Contentful core support IE11

---

packages/styled-components/src/components/primitives/Video/Video.stories.tsx
packages/styled-components/src/components/primitives/Video/Video.styled.ts
packages/styled-components/src/components/primitives/Video/Video.test.tsx
packages/styled-components/src/components/primitives/Video/Video.tsx
packages/styled-components/src/components/primitives/Video/Video.types.ts
packages/styled-components/src/components/primitives/Video/index.ts
packages/styled-components/src/components/primitives/index.ts

Styled Video

---

packages/styled-components/src/components/primitives/Badges/NumericBadge/NumericBadge.stories.tsx
packages/styled-components/src/components/primitives/Badges/NumericBadge/NumericBadge.styled.ts
packages/styled-components/src/components/primitives/Badges/NumericBadge/NumericBadge.test.tsx
packages/styled-components/src/components/primitives/Badges/NumericBadge/NumericBadge.tsx
packages/styled-components/src/components/primitives/Badges/NumericBadge/NumericBadge.types.ts
packages/styled-components/src/components/primitives/Badges/NumericBadge/index.ts
packages/styled-components/src/components/primitives/index.ts
packages/styled-components/src/styles/theme.js

Styled NumericBadge

---

packages/styled-components/src/components/primitives/Image/Image.stories.tsx
packages/styled-components/src/components/primitives/Image/Image.styled.ts
packages/styled-components/src/components/primitives/Image/Image.test.tsx
packages/styled-components/src/components/primitives/Image/Image.tsx
packages/styled-components/src/components/primitives/Image/Image.types.ts
packages/styled-components/src/components/primitives/Image/index.ts
packages/styled-components/src/components/primitives/index.ts

Styled Image

---

packages/styled-components/src/components/primitives/Asset/Asset.stories.tsx
packages/styled-components/src/components/primitives/Asset/Asset.test.tsx
packages/styled-components/src/components/primitives/Asset/Asset.tsx
packages/styled-components/src/components/primitives/Asset/Asset.types.ts
packages/styled-components/src/components/primitives/Asset/index.ts
packages/styled-components/src/components/primitives/index.ts

Styled Asset

---

packages/styled-components/src/components/primitives/List/List.stories.tsx
packages/styled-components/src/components/primitives/List/List.styled.ts
packages/styled-components/src/components/primitives/List/List.test.tsx
packages/styled-components/src/components/primitives/List/List.tsx
packages/styled-components/src/components/primitives/List/List.types.ts
packages/styled-components/src/components/primitives/List/index.tsx
packages/styled-components/src/components/primitives/index.ts

Styled List

---

packages/styled-components/src/components/primitives/Avatars/AvatarText/AvatarText.styled.ts
packages/styled-components/src/components/primitives/Avatars/AvatarText/AvatarText.test.tsx
packages/styled-components/src/components/primitives/Avatars/AvatarText/AvatarText.tsx
packages/styled-components/src/utils/customCss/customCss.test.ts
packages/styled-components/src/utils/customCss/customCss.ts
packages/styled-components/src/utils/customCss/index.ts

Styled CSS override

---

packages/styled-components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.stories.tsx
packages/styled-components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.styled.ts
packages/styled-components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.test.tsx
packages/styled-components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.tsx
packages/styled-components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.types.ts
packages/styled-components/src/components/primitives/Chat/ConversationSummary/index.tsx
packages/styled-components/src/components/primitives/index.ts

Styled ConversationSummary

---

packages/styled-components/src/components/primitives/Chat/ConversationList/ConversationList.stories.tsx
packages/styled-components/src/components/primitives/Chat/ConversationList/ConversationList.styled.ts
packages/styled-components/src/components/primitives/Chat/ConversationList/ConversationList.test.tsx
packages/styled-components/src/components/primitives/Chat/ConversationList/ConversationList.tsx
packages/styled-components/src/components/primitives/Chat/ConversationList/ConversationList.types.ts
packages/styled-components/src/components/primitives/Chat/ConversationList/index.tsx
packages/styled-components/src/components/primitives/index.ts

Styled Conversation List

---

packages/styled-components/src/components/containers/Box/Box.stories.tsx
packages/styled-components/src/components/containers/Box/Box.styled.ts
packages/styled-components/src/components/containers/Box/Box.test.tsx
packages/styled-components/src/components/containers/Box/Box.tsx
packages/styled-components/src/components/containers/Box/Box.types.ts
packages/styled-components/src/components/containers/Box/index.tsx
packages/styled-components/src/components/containers/index.tsx
packages/styled-components/src/index.ts

Styled Box

---

packages/styled-components/package.json
packages/styled-components/src/components/Components.types.ts
packages/styled-components/src/components/primitives/Button/Button.tsx
packages/styled-components/src/components/primitives/Button/Button.types.ts
packages/styled-components/src/components/primitives/Modal/Modal.stories.tsx
packages/styled-components/src/components/primitives/Modal/Modal.styled.ts
packages/styled-components/src/components/primitives/Modal/Modal.test.tsx
packages/styled-components/src/components/primitives/Modal/Modal.tsx
packages/styled-components/src/components/primitives/Modal/Modal.types.ts
packages/styled-components/src/components/primitives/Modal/index.ts
packages/styled-components/src/components/primitives/index.ts
packages/styled-components/src/styles/theme.js

Styled Modal

---

packages/styled-components/src/components/primitives/Modal/Modal.stories.tsx
packages/styled-components/src/components/primitives/Modal/Modal.test.tsx
packages/styled-components/src/components/primitives/Modal/Modal.tsx
packages/styled-components/src/components/primitives/Modal/Modal.types.ts

Styled Modal Improvements

---

packages/styled-components/src/components/containers/Grid/Grid.stories.tsx
packages/styled-components/src/components/containers/Grid/Grid.styled.ts
packages/styled-components/src/components/containers/Grid/Grid.test.tsx
packages/styled-components/src/components/containers/Grid/Grid.tsx
packages/styled-components/src/components/containers/Grid/Grid.types.ts
packages/styled-components/src/components/containers/Grid/index.ts

**Checklist**
https://trello.com/c/oiZRnNpH

Styled Grid

---

packages/styled-components/src/components/Components.styled.types.ts
packages/styled-components/src/components/Components.types.ts
packages/styled-components/src/components/containers/Grid/Grid.styled.ts
packages/styled-components/src/components/containers/Grid/Grid.test.tsx
packages/styled-components/src/components/containers/Grid/Grid.tsx
packages/styled-components/src/components/containers/Grid/Grid.types.ts
packages/styled-components/src/components/containers/SectionChild/SectionChild.stories.tsx
packages/styled-components/src/components/containers/SectionChild/SectionChild.styled.ts
packages/styled-components/src/components/containers/SectionChild/SectionChild.test.tsx
packages/styled-components/src/components/containers/SectionChild/SectionChild.tsx
packages/styled-components/src/components/containers/SectionChild/SectionChild.types.ts
packages/styled-components/src/components/containers/SectionChild/index.ts
packages/styled-components/src/components/containers/index.tsx

**Checklist**
https://trello.com/c/oiZRnNpH

Styled SectionChild

---

packages/styled-components/src/components/primitives/Form/ErrorField/ErrorField.stories.tsx
packages/styled-components/src/components/primitives/Form/ErrorField/ErrorField.styled.ts
packages/styled-components/src/components/primitives/Form/ErrorField/ErrorField.test.tsx
packages/styled-components/src/components/primitives/Form/ErrorField/ErrorField.tsx
packages/styled-components/src/components/primitives/Form/ErrorField/ErrorField.types.ts
packages/styled-components/src/components/primitives/Form/ErrorField/index.tsx
packages/styled-components/src/components/primitives/index.ts

**Checklist**
https://trello.com/c/oiZRnNpH

Styled ErrorField

---

packages/styled-components/src/components/primitives/Form/TextArea/TextArea.stories.tsx
packages/styled-components/src/components/primitives/Form/TextArea/TextArea.styled.ts
packages/styled-components/src/components/primitives/Form/TextArea/TextArea.test.tsx
packages/styled-components/src/components/primitives/Form/TextArea/TextArea.tsx
packages/styled-components/src/components/primitives/Form/TextArea/TextArea.types.ts
packages/styled-components/src/components/primitives/Form/TextArea/index.tsx
packages/styled-components/src/components/primitives/index.ts
packages/styled-components/src/styles/theme.js

**Checklist**
https://trello.com/c/95Nr1LgN/94-migrate-composer-forms-to-styled-components

Styled TextArea

---

packages/styled-components/.babelrc
packages/styled-components/src/components/containers/Grid/Grid.stories.tsx
packages/styled-components/src/components/primitives/Asset/Asset.test.tsx
packages/styled-components/src/components/primitives/Asset/Asset.tsx
packages/styled-components/src/components/primitives/Asset/Asset.types.ts
packages/styled-components/src/components/primitives/Chat/ConversationList/ConversationList.stories.tsx
packages/styled-components/src/components/primitives/Chat/ConversationList/ConversationList.test.tsx
packages/styled-components/src/components/primitives/Form/TextArea/TextArea.stories.tsx
packages/styled-components/src/components/primitives/Form/TextArea/TextArea.test.tsx
packages/styled-components/src/components/primitives/Form/TextField/TextField.stories.tsx
packages/styled-components/src/components/primitives/Form/TextField/TextField.test.tsx
packages/styled-components/src/components/primitives/Link/Link.stories.tsx
packages/styled-components/tsconfig.json

We were excluding tests and stories from typescript transpiling and that was causing the IDE to not apply the rules to those files while editing, _i.e._, we had no code completion (sometimes it works sometimes it don't 🤷‍♂️) and type checking in unit tests and stories.

Use typescript config in tests and stories too

---

packages/styled-components/src/components/primitives/Form/CurrencyField/CurrencyField.stories.tsx
packages/styled-components/src/components/primitives/Form/CurrencyField/CurrencyField.styled.ts
packages/styled-components/src/components/primitives/Form/CurrencyField/CurrencyField.test.tsx
packages/styled-components/src/components/primitives/Form/CurrencyField/CurrencyField.tsx
packages/styled-components/src/components/primitives/Form/CurrencyField/CurrencyField.types.ts
yarn.lock

**Checklist**
https://trello.com/c/95Nr1LgN

Add children to CurrencyField

---

.changeset/sour-jeans-juggle.md
packages/components/.storybook/preview.js
packages/components/package.json
packages/components/src/components/primitives/Badges/IconicBadge/IconicBadge.stories.tsx
packages/components/src/components/primitives/Badges/NumericBadge/NumericBadge.stories.tsx
packages/components/src/index.ts
packages/components/src/styles/colors.ts
packages/components/src/styles/theme.ts
packages/components/src/styles/typography.ts
packages/components/src/utils/getTheme/getTheme.test.ts
packages/components/src/utils/getTheme/getTheme.ts

define the folder to be published to npm

Fix components publishing

---

.changeset/silly-crabs-press.md
packages/components/src/components/primitives/Button/Button.styled.ts
packages/components/src/components/primitives/Button/Button.test.tsx
packages/components/src/components/primitives/Button/Button.tsx
packages/components/src/components/primitives/Button/Button.types.ts

Button add custom css

---

.changeset/slimy-hairs-explain.md
packages/components/src/components/primitives/Form/DropdownField/DropdownField.styled.ts

feat: add typography styles to dropdownfield mobile

---

.changeset/dull-elephants-jam.md
packages/components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.stories.tsx
packages/components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.styled.ts
packages/components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.test.tsx
packages/components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.tsx
packages/components/src/components/primitives/Chat/ConversationSummary/ConversationSummary.types.ts

Add customCss and messageClassName props to ConversationSummary

---

.changeset/dry-coins-check.md
packages/components/src/components/primitives/Pill/Pill.styled.ts

Fix pill padding

---

.changeset/serious-cooks-guess.md
packages/components/src/components/primitives/Modal/Modal.stories.tsx
packages/components/src/components/primitives/Modal/Modal.test.tsx
packages/components/src/components/primitives/Modal/Modal.tsx
packages/components/src/components/primitives/Modal/Modal.types.ts

Add close callback to Modal

---

.changeset/swift-mice-argue.md
packages/components/src/components/primitives/Chat/Conversation/Message/Message.styled.ts
packages/components/src/components/primitives/Chat/Conversation/Message/Message.tsx

Use DSM padding for Message component

---

packages/contentful-core/src/components/ComponentRendererWithContext/ComponentRendererWithContext.tsx
packages/contentful-core/src/components/ComponentRendererWithQuery/ComponentRendererWithQuery.tsx

* Add `context` query support for `ComponentRendererWithQuery` and `ComponentRendererWithContext`
**Checklist**

feat: Query Context - Contentful-core

---

.changeset/silly-doors-approve.md
packages/components/src/components/primitives/Toggle/Toggle.stories.tsx
packages/components/src/components/primitives/Toggle/Toggle.styled.ts
packages/components/src/components/primitives/Toggle/Toggle.test.tsx
packages/components/src/components/primitives/Toggle/Toggle.tsx
packages/components/src/components/primitives/Toggle/Toggle.types.ts
packages/components/src/components/primitives/Toggle/index.tsx
packages/components/src/components/primitives/index.ts
packages/components/src/styles/colors.ts

Create Toggle component

---

.changeset/sharp-teachers-sin.md
packages/components/src/components/primitives/Form/DropdownField/DropdownField.styled.ts
packages/components/src/components/primitives/Form/DropdownField/DropdownField.tsx

feat: add different styles for downshift dropdown

---

.changeset/hip-days-speak.md
README.md
packages/contentful-core/src/components/ComponentRendererWithQuery/ComponentRendererWithQuery.tsx

Allow for loading component on ComponentRendererWithQuery

---

.changeset/ninety-mangos-call.md
packages/contentful-core/package.json
yarn.lock

Bump apollo client ver

---

.changeset/late-sheep-glow.md
packages/components/src/components/primitives/Form/TextArea/TextArea.tsx
packages/components/src/components/primitives/Form/TextArea/TextArea.types.ts

**Checklist**
- Adding forwardRef for TextArea component to avoid warning error

feat: adding forwardRef to the TextArea component

---

.changeset/wild-forks-end.md
packages/components/src/components/primitives/Form/CheckBox/CheckBox.stories.tsx
packages/components/src/components/primitives/Form/CheckBox/CheckBox.styled.ts
packages/components/src/components/primitives/Form/CheckBox/CheckBox.test.tsx
packages/components/src/components/primitives/Form/CheckBox/CheckBox.tsx
packages/components/src/components/primitives/Form/CheckBox/CheckBox.types.ts
packages/components/src/components/primitives/Form/CheckBox/index.tsx

feat: create checkbox component

---

.changeset/polite-olives-breathe.md
packages/components/src/components/primitives/Form/CheckBox/CheckBox.styled.ts
packages/components/src/components/primitives/index.ts

feat: export checkbox from root and add cursor pointer

---

.changeset/neat-pianos-hang.md
packages/components/src/components/primitives/Form/TextField/TextField.tsx
packages/components/src/components/primitives/Form/TextFieldWithLabel/TextFieldWithLabel.tsx

feat: add rest props to the input text components

---

.changeset/breezy-moons-chew.md
packages/twilio/src/sms/TwilioSms.test.ts
packages/twilio/src/sms/TwilioSms.ts

Support buying phone number from twilio

---

.changeset/mean-beers-run.md
packages/contentful-core/package.json
yarn.lock

chore: Upgrade `contentful-core` Packages

---

packages/components/package.json
packages/components/src/theme/ComposerProvider/ComposerProvider.test.tsx
packages/components/src/theme/ComposerProvider/ComposerProvider.tsx
packages/components/src/theme/ComposerTheme/theme.ts
yarn.lock

feat: add chakra cli to autogenerate types based on theme

---

packages/components/src/components/primitives/Text/Text.test.tsx
packages/components/src/components/primitives/Text/Text.tsx
packages/components/src/components/primitives/TextPairing/TextPairing.tsx
packages/components/src/components/primitives/TextPairing/types.ts
packages/components/src/theme/ComposerTheme/Components/Text.ts

Add discoverability

---

packages/components/jest.config.js
packages/components/package.json
packages/components/src/config/jest/assetTransformer.js
packages/components/src/config/jest/assetTransformer.test.ts
packages/components/src/config/jest/assetTransformer.ts
packages/components/src/theme/ComposerProvider/ComposerProvider.tsx
yarn.lock

**Checklist**
[How to use a font in chakra](https://chakra-ui.com/guides/using-fonts#option-1-install-with-npm)

Use Inter font in components

---

packages/components/package.json
packages/components/src/theme/ComposerTheme/Colors/colors.ts
packages/components/src/theme/ComposerTheme/Components/Button.ts
packages/components/src/theme/ComposerTheme/Spacing/Spacing.stories.tsx
yarn.lock

https://impulsumvc.atlassian.net/browse/COM-188

More button improvements

---

.github/workflows/delete_storybook.yml
.github/workflows/deploy_storybook.yml

feat: use new setup cloud action

---

.github/workflows/deploy_storybook.yml
packages/components/.storybook/main.js

feat: disable chakra ui storybook

---

packages/components/src/components/primitives/Image/Image.stories.tsx
packages/components/src/components/primitives/Image/Image.test.tsx
packages/components/src/components/primitives/Image/Image.tsx
packages/components/src/components/primitives/Image/index.ts
packages/components/src/components/primitives/Image/types.ts
packages/components/src/components/primitives/index.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-208

feat: create image wrapper

---

packages/components/src/components/layouts/Box/Box.stories.tsx
packages/components/src/components/layouts/Box/Box.test.tsx
packages/components/src/components/layouts/Box/Box.tsx
packages/components/src/components/layouts/Box/index.ts
packages/components/src/components/layouts/Box/types.ts
packages/components/src/components/layouts/Flex/Flex.stories.tsx
packages/components/src/components/layouts/Flex/Flex.test.tsx
packages/components/src/components/layouts/Flex/Flex.tsx
packages/components/src/components/layouts/Flex/index.ts
packages/components/src/components/layouts/Flex/types.ts
packages/components/src/components/layouts/Grid/Grid.stories.tsx
packages/components/src/components/layouts/Grid/Grid.test.tsx
packages/components/src/components/layouts/Grid/Grid.tsx
packages/components/src/components/layouts/Grid/index.ts
packages/components/src/components/layouts/Grid/types.ts
packages/components/src/components/layouts/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-205

[COM-205] Layout components

---

packages/components/src/components/primitives/Tabs/Tabs.stories.tsx
packages/components/src/components/primitives/Tabs/Tabs.test.tsx
packages/components/src/components/primitives/Tabs/Tabs.tsx
packages/components/src/components/primitives/Tabs/index.ts
packages/components/src/components/primitives/Tabs/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Components/Tabs.ts
packages/components/src/theme/ComposerTheme/Components/index.ts
packages/components/src/theme/ComposerTheme/Shadows/shadows.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-143

Implement Tabs component

---

packages/components/src/components/primitives/Badge/Badge.stories.tsx
packages/components/src/components/primitives/Badge/Badge.test.tsx
packages/components/src/components/primitives/Badge/Badge.tsx
packages/components/src/components/primitives/Badge/index.ts
packages/components/src/components/primitives/Badge/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Colors/colors.ts
packages/components/src/theme/ComposerTheme/Components/Badge.ts
packages/components/src/theme/ComposerTheme/Components/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-131
http://localhost:8080/?path=/story/components-primitives-badge--all

[COM-131] Implementation of Badge component

---

packages/components/src/components/primitives/Avatar/Avatar.stories.tsx
packages/components/src/components/primitives/Avatar/Avatar.test.tsx
packages/components/src/components/primitives/Avatar/Avatar.tsx
packages/components/src/components/primitives/Avatar/index.ts
packages/components/src/components/primitives/Avatar/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Colors/colors.ts
packages/components/src/theme/ComposerTheme/Components/Avatar.ts
packages/components/src/theme/ComposerTheme/Components/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-126

[COM-126] Avatar component

---

.changeset/lemon-olives-jam.md
packages/components/.storybook/preview.js
packages/components/package.json
packages/components/src/theme/ComposerProvider/ComposerProvider.tsx
packages/components/src/theme/ComposerProvider/types.ts
packages/components/src/theme/ComposerTheme/styles.ts
packages/components/src/theme/ComposerTheme/types.ts

Move font family out of project

---

packages/components/src/components/primitives/Alert/Alert.stories.tsx
packages/components/src/components/primitives/Alert/Alert.test.tsx
packages/components/src/components/primitives/Alert/Alert.tsx
packages/components/src/components/primitives/Alert/index.ts
packages/components/src/components/primitives/Alert/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Components/Alert.ts
packages/components/src/theme/ComposerTheme/Components/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-129
http://localhost:8080/?path=/story/components-primitives-alert--all

[COM-129] Implement Alert Component

---

.changeset/ten-rats-confess.md
packages/components/package.json
packages/components/tsconfig.json

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-323

Library bundle shouldn't include tests and stories

---

.changeset/smooth-tomatoes-tap.md
.changeset/wicked-clouds-walk.md
packages/components/src/theme/ComposerTheme/Components/Avatar.ts
packages/components/src/theme/ComposerTheme/Components/Badge.ts
packages/components/src/theme/ComposerTheme/Components/Button.ts
packages/components/src/theme/ComposerTheme/Components/Tabs.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-324?redirectCount=1

Text style doesn't apply for chakra components

---

.changeset/chilly-cameras-pull.md
packages/components/package.json
packages/components/scripts/generate_theme_typings.sh

**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-322

feat: create script to detect when chakra ui cli package is installed

---

.changeset/quiet-fishes-bow.md
packages/components/src/components/primitives/Select/Select.stories.tsx
packages/components/src/components/primitives/Select/Select.test.tsx
packages/components/src/components/primitives/Select/Select.tsx
packages/components/src/components/primitives/Select/index.ts
packages/components/src/components/primitives/Select/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Components/Select.ts
packages/components/src/theme/ComposerTheme/Components/index.ts
packages/components/src/theme/ComposerTheme/styles.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-138
http://localhost:8080/?path=/story/components-primitives-select--all

[COM-138] Select component implementation

---

.changeset/gorgeous-carrots-whisper.md
packages/components/src/components/primitives/Card/Card.stories.tsx
packages/components/src/components/primitives/Card/Card.test.tsx
packages/components/src/components/primitives/Card/Card.tsx
packages/components/src/components/primitives/Card/index.ts
packages/components/src/components/primitives/Card/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Components/Card.ts
packages/components/src/theme/ComposerTheme/Components/index.ts
packages/components/src/theme/ComposerTheme/Radius/radius.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-207

Implement Card component

---

packages/components/src/components/primitives/Checkbox/Checkbox.stories.tsx
packages/components/src/components/primitives/Checkbox/Checkbox.test.tsx
packages/components/src/components/primitives/Checkbox/Checkbox.tsx
packages/components/src/components/primitives/Checkbox/index.ts
packages/components/src/components/primitives/Checkbox/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerProvider/ComposerProvider.tsx
packages/components/src/theme/ComposerTheme/Components/Checkbox.ts
packages/components/src/theme/ComposerTheme/Components/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-134
http://localhost:8080/?path=/story/components-primitives-checkbox--all

[COM-134] checkbox component

---

.changeset/sixty-carpets-relate.md
packages/components/.storybook/preview.js
packages/components/src/hooks/index.ts
packages/components/src/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-328

[COM-328] Expose use breakpoint value

---

.changeset/angry-seahorses-travel.md
packages/components/package.json

We were not transpiling tabler icon files

Transpile js files

---

.changeset/nasty-cougars-boil.md
packages/components/src/theme/ComposerProvider/ComposerProvider.tsx
packages/components/src/theme/ComposerProvider/types.ts

Add resetCSS prop to provider

---

.changeset/gold-bobcats-relate.md
packages/components/.storybook/main.js
packages/components/package.json
yarn.lock

Update storybook and deprecate postcss

---

.changeset/cold-goats-deny.md
packages/components/babel.config.js
packages/components/src/components/primitives/Text/Text.stories.tsx
packages/components/src/components/primitives/Text/Text.tsx
packages/components/src/components/primitives/Text/types.ts
packages/components/src/components/primitives/TextPairing/TextPairing.stories.tsx
packages/components/src/components/primitives/TextPairing/TextPairing.tsx
packages/components/src/components/primitives/TextPairing/types.ts
packages/components/src/hooks/index.ts
packages/components/src/hooks/useResponsiveValue/index.ts
packages/components/src/hooks/useResponsiveValue/useResponsiveValue.test.ts
packages/components/src/hooks/useResponsiveValue/useResponsiveValue.ts
packages/components/src/theme/ComposerTheme/Components/Text.ts
packages/components/src/theme/ComposerTheme/Components/TextPairing.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-345

[COM-345] Responsive variant for Text and TextPairing

---

.changeset/serious-sheep-sing.md
packages/components/src/hooks/useResponsiveValue/useResponsiveValue.ts

Fix: Add default breakpoint

---

.gitignore
package.json
yarn.lock

Move to [Turbo](https://turborepo.org/) but keep lerna for package versioning and publishing.
Question: Should we not commit build artifacts?

Port to turbo repo

---

deploy/storybook/Dockerfile

fix: remove scope from docker sb build command

---

.changeset/three-ways-run.md
packages/components/src/components/primitives/Select/Select.stories.tsx
packages/components/src/components/primitives/Select/Select.tsx
packages/components/src/components/primitives/Select/types.ts
packages/components/src/theme/ComposerTheme/Components/Select.ts
packages/components/src/theme/ComposerTheme/styles.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-350
http://localhost:8080/?path=/story/components-primitives-select--playground&args=iconSize:l

[COM-350] Add iconSize prop to Select component

---

.eslintignore
.github/workflows/chromatic.yml
.github/workflows/linter.yml
packages/components/src/components/layouts/Box/types.ts
packages/components/src/components/layouts/Flex/types.ts
packages/components/src/components/layouts/Grid/types.ts
packages/components/src/components/layouts/Section/types.ts
packages/components/src/components/primitives/Image/types.ts
packages/components/src/components/primitives/Tabs/Tabs.tsx
packages/components/src/components/primitives/Tabs/types.ts
packages/firestore/src/db/FirestoreDb.ts
packages/plaid/src/client/Plaid.ts
packages/twilio/src/conversations/TwilioConversation.test.ts
packages/twilio/src/sms/TwilioSms.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-355

[COM-355] Enable linter as action and fix issues

---

.changeset/tame-ants-add.md
packages/components/src/components/primitives/Radio/Radio.stories.tsx
packages/components/src/components/primitives/Radio/Radio.test.tsx
packages/components/src/components/primitives/Radio/Radio.tsx
packages/components/src/components/primitives/Radio/index.ts
packages/components/src/components/primitives/Radio/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Components/Radio.ts
packages/components/src/theme/ComposerTheme/Components/index.ts

**Checklist**
**What is the ticket / issue associated with this change?** 
[https://impulsumvc.atlassian.net/browse/COM-135](https://impulsumvc.atlassian.net/browse/COM-135)

COM-135 feat: Adding Radio button component

---

.changeset/eight-tables-nail.md
.eslintrc.js
.github/workflows/chromatic.yml
packages/components/src/components/primitives/Accordion/Accordion.stories.tsx
packages/components/src/components/primitives/Tag/Tag.stories.tsx
packages/components/src/components/primitives/Tag/Tag.test.tsx
packages/components/src/components/primitives/Tag/Tag.tsx
packages/components/src/components/primitives/Tag/index.tsx
packages/components/src/components/primitives/Tag/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Components/Tag.ts
packages/components/src/theme/ComposerTheme/Components/index.ts

**Checklist**
- [] Bug fix (non-breaking change which fixes an issue)
https://impulsumvc.atlassian.net/browse/COM-142
http://localhost:8080/?path=/story/components-primitives-tag--all&globals=backgrounds.grid:false

Com 142 tag component

---

.changeset/spicy-plants-rule.md
packages/components/src/components/primitives/Progress/Progress.stories.tsx
packages/components/src/components/primitives/Progress/Progress.test.tsx
packages/components/src/components/primitives/Progress/Progress.tsx
packages/components/src/components/primitives/Progress/index.ts
packages/components/src/components/primitives/Progress/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Components/Progress.ts
packages/components/src/theme/ComposerTheme/Components/index.ts

**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-127

feat: create progress component

---

packages/components/package.json
yarn.lock

https://impulsumvc.atlassian.net/browse/COM-392

[COM-392 ]Update chakra to latest version

---

.changeset/grumpy-snails-accept.md
packages/components/scripts/generate_icons.js
packages/components/src/components/primitives/Checkbox/Checkbox.stories.tsx
packages/components/src/components/primitives/Checkbox/Checkbox.tsx
packages/components/src/components/primitives/Divider/Divider.stories.tsx
packages/components/src/components/primitives/Icons/Icons.stories.tsx
packages/components/src/components/primitives/Icons/types.ts
packages/components/src/components/primitives/Input/Input.stories.tsx
packages/components/src/components/primitives/Link/Link.tsx
packages/components/src/components/primitives/Select/Select.tsx
packages/components/src/theme/ComposerTheme/Components/Alert.ts
packages/components/src/theme/ComposerTheme/Components/Checkbox.ts
packages/components/src/theme/ComposerTheme/Components/Icon.ts
packages/components/src/theme/ComposerTheme/Components/Input.ts
packages/components/src/theme/ComposerTheme/Components/Link.ts
packages/components/src/theme/ComposerTheme/Components/Select.ts
packages/components/src/theme/ComposerTheme/Components/Tag.ts
packages/components/src/theme/ComposerTheme/styles.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-390

Icon sizes

---

.changeset/four-walls-arrive.md
.editorconfig
packages/components/src/components/primitives/Alert/Alert.stories.tsx
packages/components/src/components/primitives/Alert/Alert.test.tsx
packages/components/src/components/primitives/Alert/Alert.tsx
packages/components/src/components/primitives/Alert/types.ts
packages/components/src/theme/ComposerTheme/Components/Alert.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-371

Alert component issues

---

.changeset/few-schools-shout.md
packages/components/src/components/primitives/Slider/Slider.stories.tsx
packages/components/src/theme/ComposerTheme/Components/Slider.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-381

Slider handler size

---

.changeset/gentle-turkeys-train.md
packages/components/src/components/primitives/Accordion/Accordion.stories.tsx
packages/components/src/components/primitives/Accordion/Accordion.tsx
packages/components/src/theme/ComposerTheme/Components/Accordion.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-385

Accordion component issues

---

.changeset/five-lemons-doubt.md
packages/components/src/components/layouts/Flex/index.ts
packages/components/src/components/primitives/Breadcrumb/Breadcrumb.stories.tsx
packages/components/src/components/primitives/Breadcrumb/Breadcrumb.test.tsx
packages/components/src/components/primitives/Breadcrumb/Breadcrumb.tsx
packages/components/src/components/primitives/Breadcrumb/types.ts
packages/components/src/theme/ComposerTheme/Components/Breadcrumb.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-383
The `Breadcrumb` component has been re-implemented, instead of being composed from outside it now accepts a list of items to show.

[COM-383] Reimplement Breadcrumb component

---

.changeset/old-students-hug.md
packages/components/src/theme/ComposerTheme/styles.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-397

[COM-397] Fix text-body style line heights

---

.changeset/witty-doors-fetch.md
packages/components/src/components/primitives/Button/Button.stories.tsx
packages/components/src/components/primitives/Link/Link.stories.tsx
packages/components/src/components/primitives/Link/Link.tsx
packages/components/src/components/primitives/Link/types.ts
packages/components/src/theme/ComposerTheme/Components/Link.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-301

Support Button variants in Link component

---

.github/workflows/chromatic.yml
.github/workflows/skip_chromatic.yml

- https://impulsumvc.atlassian.net/browse/COM-403
Added github actions that will allow to merge PR when required UI Tests are not executed

[COM-403] Add ghost checks

---

.changeset/lovely-planes-bathe.md
CODEOWNERS
packages/components/src/components/primitives/Button/Button.stories.tsx
packages/components/src/components/primitives/Button/types.ts
packages/components/src/theme/ComposerTheme/Components/Button.ts
packages/components/src/theme/ComposerTheme/Components/Link.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-396

Fix Button sizes

---

.github/workflows/skip_chromatic.yml

https://impulsumvc.atlassian.net/browse/COM-403
Only execute the skip chromatic if the paths changed do not contain the components package

[COM-403] Improve skip chromatic path management

---

.changeset/great-walls-love.md
CODEOWNERS
packages/components/src/theme/ComposerTheme/Components/Breadcrumb.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-409

Fix Breadcrumb

---

.changeset/wise-dryers-unite.md
CODEOWNERS
packages/components/src/components/primitives/Button/Button.stories.tsx
packages/components/src/components/primitives/Button/Button.tsx
packages/components/src/components/primitives/Button/types.ts
packages/components/src/theme/ComposerTheme/Components/Button.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-410

Fix Button

---

.changeset/serious-snails-exercise.md
packages/components/.swcrc

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-394

[COM-394] Fix aliased paths

---

.changeset/soft-flies-bow.md
package.json
packages/components/package.json

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-394

[COM-394] Emit types on release

---

.changeset/rude-panthers-kick.md
packages/components/package.json
packages/components/scripts/generate_theme_typings.sh
packages/components/src/components/primitives/TextPairing/TextPairing.stories.tsx
packages/components/src/components/primitives/TextPairing/TextPairing.tsx
packages/components/src/components/primitives/TextPairing/types.ts
yarn.lock

Allow theme color for label and subLabel in TextPairing

---

.changeset/great-pillows-count.md
packages/components/package.json
packages/components/src/components/primitives/CloseButton/CloseButton.tsx
packages/components/src/components/primitives/Modal/Modal.stories.tsx
packages/components/src/components/primitives/Modal/Modal.test.tsx
packages/components/src/components/primitives/Modal/Modal.tsx
packages/components/src/components/primitives/Modal/index.ts
packages/components/src/components/primitives/Modal/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerProvider/ComposerProvider.tsx
packages/components/src/theme/ComposerTheme/Components/Modal.ts
packages/components/src/theme/ComposerTheme/Components/index.ts
yarn.lock

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-297
http://localhost:8080/?path=/story/components-primitives-modal--all

[COM-297] Modal component

---

.changeset/tricky-rocks-run.md
packages/components/.vscode/settings.json
packages/components/src/components/primitives/IconButton/IconButton.stories.tsx
packages/components/src/components/primitives/IconButton/IconButton.test.tsx
packages/components/src/components/primitives/IconButton/IconButton.tsx
packages/components/src/components/primitives/IconButton/index.ts
packages/components/src/components/primitives/IconButton/types.ts
packages/components/src/components/primitives/index.ts
packages/components/src/theme/ComposerTheme/Components/Button.ts
packages/components/src/theme/ComposerTheme/Components/IconButton.ts
packages/components/src/theme/ComposerTheme/Components/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-133

[COM-133] Implementation of IconButton component

---

packages/components/package.json

Include scripts folder in the release

---

.changeset/brave-crabs-drum.md
packages/components/src/components/primitives/Card/Card.stories.tsx

**Checklist**
- [] New feature (non-breaking change which adds functionality)
the stories in the `Card` component was crashing,  storybook complained when passing the `Box` component by `children` prop in the story config section, so my fix was to move that part into `Template` component.

Hotfix: Fixed error in card component stories

---

packages/components/src/theme/ComposerTheme/Components/Textarea.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-435
https://5eed577398d08d0022b52d76-kdmfzuggdy.chromatic.com/?path=/story/components-primitives-textarea--all

Hotfix: Fix the styles on focus in the textarea component

---

.changeset/ninety-cheetahs-thank.md
packages/components/.storybook/preview.js
packages/components/.swcrc
packages/components/package.json
yarn.lock

Fix storybook class and function names

---

.changeset/big-mangos-leave.md
packages/components/src/components/primitives/Button/Button.stories.tsx
packages/components/src/components/primitives/Link/Link.stories.tsx
packages/components/src/components/primitives/Link/Link.tsx
packages/components/src/theme/ComposerTheme/Components/Link.ts

**Checklist**
- https://impulsumvc.atlassian.net/browse/COM-478

[COM-478] Remove unnecessary link child wrapper

---

.changeset/ten-ears-joke.md
packages/components/src/components/primitives/Link/Link.stories.tsx
packages/components/src/components/primitives/Tag/Tag.stories.tsx
packages/components/src/components/primitives/Tag/Tag.test.tsx
packages/components/src/components/primitives/Tag/Tag.tsx
packages/components/src/components/primitives/Tag/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-465
I need to update the stories since we are using composition and I must do this:
From this:
```jsx
<Tag
leftIcon={}
label=""
/>
```
To this:
```jsx
<Tag>
<Tag.LeftIcon />
<Tag.Label />
<Tag>
```
If I don’t do that I will get an error,  due to implementation changes. @tkanzakic  let me know if you agree to push the updated stories

COM-465: Refactor tag component to use composition

---

.changeset/tame-mails-melt.md
packages/components/src/theme/ComposerTheme/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-493

[COM-493] Theme partial props

---

.changeset/curvy-bats-call.md
packages/components/src/components/primitives/Input/Input.stories.tsx
packages/components/src/theme/ComposerTheme/Components/Input.ts
packages/components/src/theme/ComposerTheme/Components/PinInput.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-476
https://5eed577398d08d0022b52d76-abspfeavny.chromatic.com/?path=/story/components-primitives-input--all

Com 476 fix input and pin input styles

---

.changeset/shaggy-forks-think.md
packages/components/src/hooks/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-492

[COM-492] Expose createBreakpoints function

---

.changeset/popular-candles-cheer.md
package.json
packages/analytics/src/AnalyticsProvider.tsx
packages/components/package.json
packages/components/src/components/notifications/Toast/types.ts
packages/components/src/components/notifications/Toast/useToast.test.tsx
packages/components/src/components/primitives/Checkbox/Checkbox.stories.tsx
packages/components/src/components/primitives/Input/Input.tsx
packages/components/src/components/primitives/Modal/Modal.stories.tsx
packages/components/src/theme/ComposerTheme/Colors/Colors.stories.tsx
packages/components/src/theme/ComposerTheme/Components/Input.ts
yarn.lock

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-569
**Other information**
Chakra migration guide - https://chakra-ui.com/guides/migration

[COM-569] Upgrade chakra packages to latest version to support React 18

---

.changeset/hip-shoes-repeat.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-584

COM-584: Escape pipe characters

---

.changeset/five-cooks-accept.md
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-580
we are going to remove `MdxPage` content type from `contentful` but we need to get this PR merged and until then remove this content type.

COM-580: Removed MdxPage from getRouteBySlug query

---

.changeset/clean-dots-check.md
packages/nextjs-contentful-renderer/config/jest/setupTests.ts
packages/nextjs-contentful-renderer/src/utils/getApolloClient/getApolloClient.test.ts
packages/nextjs-contentful-renderer/src/utils/getApolloClient/getApolloClient.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-595

COM-595: Add environment param to apolloClient instance

---

.changeset/cold-hornets-whisper.md
packages/components/src/components/primitives/Breadcrumb/Breadcrumb.stories.tsx
packages/components/src/components/primitives/Link/Link.stories.tsx
packages/components/src/components/primitives/Link/Link.test.tsx
packages/components/src/components/primitives/Link/Link.tsx
packages/components/src/components/primitives/Link/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-593

Com 593 refactor link component

---

.changeset/real-mice-doubt.md
packages/components/src/components/primitives/Button/Button.stories.tsx
packages/components/src/components/primitives/Button/Button.tsx
packages/components/src/components/primitives/Button/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-594

Com 594 refactor button component

---

.changeset/orange-lies-shake.md
packages/components/package.json
packages/components/src/components/primitives/Button/types.ts
packages/components/src/components/primitives/Link/Link.stories.tsx
packages/components/src/components/primitives/Link/types.ts
packages/components/src/hooks/index.ts
packages/components/src/theme/ComposerTheme/Components/Button.ts
packages/components/src/theme/ComposerTheme/Components/Link.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-604

[COM-604] Add link variant to Button

---

.changeset/late-chicken-sneeze.md
packages/nextjs-contentful-renderer/package.json
packages/nextjs-contentful-renderer/src/MdxRenderer/MdxRenderer.tsx
yarn.lock

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-618

[COM-618] Expose blocks in MdxRenderer

---

.changeset/many-suns-remain.md
packages/blocks/src/CookieBanner/CookieBanner.stories.tsx
packages/blocks/src/Navigation/BaseNavigation.tsx
packages/blocks/src/Navigation/DesktopNavigation.tsx
packages/blocks/src/Navigation/Navigation.stories.tsx
packages/blocks/src/Navigation/Navigation.test.tsx
packages/blocks/src/Navigation/Navigation.tsx
packages/blocks/src/Navigation/index.ts
packages/blocks/src/Navigation/types.ts
packages/blocks/src/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-585

[COM-585] Navigation Block

---

.changeset/cold-mice-switch.md
packages/components/src/components/primitives/TextPairing/TextPairing.stories.tsx
packages/components/src/components/primitives/TextPairing/TextPairing.tsx
packages/components/src/components/primitives/TextPairing/types.ts

Add textAlign property to TextPairing

---

.changeset/wise-cycles-fetch.md
packages/blocks/src/BrandLogos/BrandLogos.stories.tsx
packages/blocks/src/BrandLogos/BrandLogos.test.tsx
packages/blocks/src/BrandLogos/BrandLogos.tsx
packages/blocks/src/BrandLogos/index.ts
packages/blocks/src/BrandLogos/types.ts
packages/blocks/src/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-590

[COM-590] BrandLogos block

---

.changeset/smooth-sloths-serve.md
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/fragments.ts

https://impulsumvc.atlassian.net/browse/COM-623

[COM-623] Rename Mdx to Model

---

.changeset/fast-ghosts-design.md
packages/blocks/src/BrandLogos/BrandLogos.stories.tsx
packages/blocks/src/BrandLogos/BrandLogos.test.tsx
packages/blocks/src/BrandLogos/BrandLogos.tsx
packages/blocks/src/BrandLogos/types.ts
packages/blocks/src/Hero/Hero.stories.tsx
packages/blocks/src/Hero/Hero.test.tsx
packages/blocks/src/Hero/Hero.tsx
packages/blocks/src/Hero/types.ts
packages/blocks/src/Navigation/Navigation.tsx
packages/components/src/components/primitives/TextPairing/types.ts

Unify Hero Image properties

---

.changeset/nervous-apricots-kneel.md
packages/nextjs-contentful-renderer/src/getPageContent/getPageContent.test.ts
packages/nextjs-contentful-renderer/src/getPageContent/getPageContent.ts

fix: Config navbar when page loaded from cookies

---

.changeset/famous-vans-press.md
packages/components/src/theme/ComposerTheme/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-576

COM-576: Add breakpoint and styles properties in theme types

---

package.json
yarn.lock

Fix a [security issue](https://github.com/cmpsr/composer/pull/491). Closes #491

Update lerna to latest version

---

packages/nextjs-contentful-renderer/src/configFooter/configFooter.test.ts
packages/nextjs-contentful-renderer/src/configFooter/configFooter.ts
packages/nextjs-contentful-renderer/src/configFooter/index.ts
packages/nextjs-contentful-renderer/src/configNavbar/configNavbar.test.ts
packages/nextjs-contentful-renderer/src/configNavbar/configNavbar.ts
packages/nextjs-contentful-renderer/src/getPageContent/getPageContent.test.ts
packages/nextjs-contentful-renderer/src/getPageContent/getPageContent.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/getPageById.test.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/getPageById.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/types.ts
packages/nextjs-contentful-renderer/src/utils/insertSection/index.ts
packages/nextjs-contentful-renderer/src/utils/insertSection/insertSection.test.ts
packages/nextjs-contentful-renderer/src/utils/insertSection/insertSection.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-555

COM-555: Add sopport for footer

---

.changeset/weak-jokes-suffer.md
packages/components/src/components/primitives/Accordion/index.ts

Export Accordion Props

---

.changeset/cyan-apples-melt.md
packages/blocks/src/Footer/Footer.tsx

feat: justify footer content

---

.changeset/eighty-moose-allow.md
packages/components/src/theme/ComposerTheme/Components/InlineAlert.ts

Fix inline alert text style

---

.changeset/breezy-bobcats-help.md
packages/components/src/theme/ComposerTheme/styles.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-645

update font size for body-meta-medium styles

---

.changeset/serious-flowers-sell.md
packages/blocks/src/BrandLogos/BrandLogos.stories.tsx
packages/blocks/src/BrandLogos/BrandLogos.test.tsx
packages/blocks/src/BrandLogos/BrandLogos.tsx
packages/blocks/src/BrandLogos/types.ts
packages/blocks/src/Hero/Hero.stories.tsx
packages/blocks/src/Hero/Hero.test.tsx
packages/blocks/src/Hero/Hero.tsx
packages/blocks/src/Hero/types.ts
packages/blocks/src/MediaBlock/MediaBlock.stories.tsx
packages/blocks/src/MediaBlock/MediaBlock.test.tsx
packages/blocks/src/MediaBlock/MediaBlock.tsx
packages/blocks/src/MediaBlock/types.ts
packages/components/src/components/primitives/Accordion/Accordion.stories.tsx
packages/components/src/components/primitives/Modal/Modal.stories.tsx
packages/components/src/components/primitives/TextPairing/TextPairing.stories.tsx
packages/components/src/components/primitives/TextPairing/TextPairing.test.tsx
packages/components/src/components/primitives/TextPairing/TextPairing.tsx
packages/components/src/components/primitives/TextPairing/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-649

Update TextPairing implementation to use dot notation / composition

---

.changeset/hungry-horses-attend.md
packages/components/src/components/primitives/TextPairing/TextPairing.tsx
packages/components/src/components/primitives/TextPairing/types.ts
packages/components/src/theme/ComposerTheme/Components/TextPairing.ts

Add columnGap to TextPairing parts

---

.changeset/stupid-mirrors-rescue.md
packages/nextjs-contentful-renderer/README.md
packages/nextjs-contentful-renderer/src/getStaticRoutes/getStaticRoutes.test.ts
packages/nextjs-contentful-renderer/src/getStaticRoutes/getStaticRoutes.ts
packages/nextjs-contentful-renderer/src/getStaticRoutes/index.ts
packages/nextjs-contentful-renderer/src/index.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.test.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/types.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getStaticRoutes/getStaticRoutes.test.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getStaticRoutes/getStaticRoutes.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getStaticRoutes/index.ts
packages/nextjs-contentful-renderer/src/utils/contentful/index.ts
packages/nextjs-contentful-renderer/src/utils/getPageId/getPageId.test.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-661

Com 661 get static routes

---

.changeset/mighty-pens-reply.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-665

[COM-665] Improve mdx generation

---

.changeset/wise-worms-sip.md
packages/blocks/src/Navigation/BaseNavigation.tsx
packages/blocks/src/Navigation/DesktopNavigation.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-664

[COM-664] Spread properties for Navigation block anchors

---

.changeset/violet-pens-share.md
packages/components/src/components/primitives/NumberedList/NumberedList.stories.tsx
packages/components/src/components/primitives/NumberedList/NumberedList.test.tsx
packages/components/src/components/primitives/NumberedList/NumberedList.tsx
packages/components/src/components/primitives/NumberedList/index.ts
packages/components/src/components/primitives/NumberedList/types.ts
packages/components/src/components/primitives/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-666

NumberedList

---

.changeset/heavy-pots-double.md
packages/components/src/theme/ComposerTheme/Components/TextPairing.ts

TextPairing column gap should be applied from base breakpoint

---

.changeset/nine-boats-try.md
packages/blocks/src/Testimonial/Testimonial.stories.tsx
packages/blocks/src/Testimonial/Testimonial.test.tsx
packages/blocks/src/Testimonial/Testimonial.tsx
packages/blocks/src/Testimonial/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-713

[COM-713] Refactor Testimonial to use dot notation

---

.changeset/yellow-needles-buy.md
packages/blocks/src/CookieBanner/CookieBanner.stories.tsx
packages/blocks/src/CookieBanner/CookieBanner.test.tsx
packages/blocks/src/CookieBanner/CookieBanner.tsx
packages/blocks/src/CookieBanner/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-716

[COM-716] Refactor CookieBanner to use dot notation

---

.changeset/rich-plants-argue.md
packages/blocks/src/Footer/Footer.stories.tsx
packages/blocks/src/Footer/Footer.test.tsx
packages/blocks/src/Footer/Footer.tsx
packages/blocks/src/Footer/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-719

[COM-719] Change Footer to use dot notation

---

.changeset/gorgeous-moons-rhyme.md
packages/blocks/src/Quote/Quote.stories.tsx
packages/blocks/src/Quote/Quote.test.tsx
packages/blocks/src/Quote/Quote.tsx
packages/blocks/src/Quote/index.ts
packages/blocks/src/Quote/types.ts
packages/blocks/src/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-722

[COM-722] Implement Quote block

---

.changeset/wet-pillows-switch.md
packages/components/src/components/primitives/Accordion/Accordion.tsx
packages/components/src/components/primitives/Accordion/types.ts
packages/components/src/theme/ComposerTheme/Components/Accordion.ts

Close #400 
**Checklist**
https://impulsumvc.atlassian.net/browse/COM-405

[COM-405] Fix AccordionIcon to use tabler icons instead of chakra implementation

---

.changeset/fair-moose-hope.md
packages/components/package.json
packages/components/src/components/primitives/Accordion/Accordion.tsx
packages/components/src/components/primitives/Avatar/Avatar.tsx
packages/components/src/components/primitives/Avatar/types.ts
packages/components/src/components/primitives/ProgressCircular/ProgressCircular.tsx
packages/components/src/components/primitives/Tag/Tag.tsx
packages/components/src/theme/ComposerTheme/Components/Avatar.ts
packages/components/src/theme/ComposerTheme/Components/Input.ts
packages/components/src/theme/ComposerTheme/Components/Tag.ts
packages/components/src/theme/ComposerTheme/Components/index.ts
yarn.lock

https://impulsumvc.atlassian.net/browse/COM-725

[COM-725] Update chakra-ui to latest version

---

.changeset/quick-spiders-thank.md
packages/signalwire/.gitignore
packages/signalwire/.swcrc
packages/signalwire/CHANGELOG.md
packages/signalwire/README.md
packages/signalwire/config/jest/cssTransform.js
packages/signalwire/config/jest/setupTests.ts
packages/signalwire/jest.config.js
packages/signalwire/package.json
packages/signalwire/src/index.ts
packages/signalwire/src/sms/SignalwireSms.test.ts
packages/signalwire/src/sms/SignalwireSms.ts
packages/signalwire/src/sms/index.test.ts
packages/signalwire/src/sms/index.ts
packages/signalwire/src/types/ClientConfig.ts
packages/signalwire/src/types/index.ts
packages/signalwire/tsconfig.json
yarn.lock

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-819

[COM-819] Integrate SignalWire API to send SMS messages

---

.changeset/loud-apples-sort.md
.changeset/proud-buses-play.md
packages/blocks/src/index.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-760

[COM-7607] Handle components when generating mdx

---

.changeset/metal-carrots-move.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

Merge nested props

---

.changeset/chilly-toes-rule.md
.changeset/sharp-otters-walk.md
packages/components/src/theme/ComposerProvider/ComposerProvider.tsx
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts
packages/nextjs-contentful-renderer/src/utils/mergeDeep/index.ts
packages/nextjs-contentful-renderer/src/utils/mergeDeep/mergeDeep.test.ts
packages/nextjs-contentful-renderer/src/utils/mergeDeep/mergeDeep.ts

Replace lodash.merge with custom implementation

---

.changeset/rotten-zoos-chew.md
packages/components/src/hooks/index.ts

**Checklist**
Having this hook available will simplify the implementation of some editor in the composer contentful app

Re-export chakra-ui useTheme

---

.changeset/grumpy-guests-explode.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

https://impulsumvc.atlassian.net/browse/COM-850

Add support for Bullets

---

.changeset/fuzzy-doors-exercise.md
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/getPageById.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/types.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/insertSection/insertSection.test.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/insertSection/insertSection.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-863

[COM-859] Load propsValue for Navigation and Footer

---

.changeset/brave-chicken-trade.md
packages/blocks/src/ColumnLayout/ColumnLayout.stories.tsx
packages/blocks/src/ColumnLayout/ColumnLayout.test.tsx
packages/blocks/src/ColumnLayout/ColumnLayout.tsx
packages/blocks/src/ColumnLayout/types.ts
packages/blocks/src/Hero/Hero.tsx
packages/blocks/src/MediaBlock/MediaBlock.stories.tsx
packages/blocks/src/MediaBlock/MediaBlock.test.tsx
packages/blocks/src/MediaBlock/MediaBlock.tsx
packages/blocks/src/MediaBlock/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-859

[COM-859] Add overline text to MediaBlock and ColumnLayout

---

.changeset/wicked-mugs-cheat.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

**Checklist**
**What is the ticket / issue associated with this change?** 
https://impulsumvc.atlassian.net/browse/COM-872

[COM-872] Replace ENV_VAR field type with process.env

---

.changeset/witty-toes-smell.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-861

[COM-861] Add support for Column type to generateMdx

---

.changeset/big-shoes-arrive.md
packages/blocks/src/ColumnLayout/ColumnLayout.stories.tsx
packages/blocks/src/ColumnLayout/ColumnLayout.tsx

Add default value to flexWrap

---

.changeset/light-lamps-melt.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

Add support for Images field type

---

.changeset/warm-olives-protect.md
packages/components/src/components/navigation/Link/Link.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-927

[COM-927] Add width inherit to Link component

---

.changeset/red-wasps-cover.md
packages/blocks/package.json

Bump peer dependency @cmpsr/components in @cmpsr/blocks

---

.changeset/silly-bulldogs-sort.md
packages/signalwire/src/VideoChat/components/Chat/Chat.tsx
packages/signalwire/src/VideoChat/hooks/useChat/types.ts
packages/signalwire/src/VideoChat/hooks/useChat/useChat.tsx
packages/signalwire/src/VideoChat/utils/client/getChatToken/getChatToken.ts
packages/signalwire/src/VideoChat/utils/client/getChatToken/index.ts
packages/signalwire/src/VideoChat/utils/client/index.ts
packages/signalwire/src/VideoChat/utils/client/isRoomAvailable/isRoomAvailable.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-952

[COM-953] Fix messages scroll

---

.changeset/tough-dancers-smell.md
packages/blocks/src/Navigation/components/NavigationLinks.tsx

Update Navigation.Links to accept spread properties

---

.changeset/silent-plums-dress.md
packages/blocks/src/Navigation/Navigation.stories.tsx
packages/blocks/src/Navigation/Navigation.tsx
packages/blocks/src/Navigation/components/NavigationLinks.tsx
packages/blocks/src/Navigation/types.ts

Add new showDividers property to NavigationLinks

---

.changeset/great-pugs-applaud.md
packages/blocks/.swcrc
packages/blocks/src/AccordionGallery/AccordionGallery.test.tsx
packages/blocks/src/BrandLogos/BrandLogos.test.tsx
packages/blocks/src/ColumnLayout/ColumnLayout.test.tsx
packages/blocks/src/CookieBanner/CookieBanner.test.tsx
packages/blocks/src/Footer/Footer.test.tsx
packages/blocks/src/Hero/Hero.test.tsx
packages/blocks/src/HighlightedText/HighlightedText.test.tsx
packages/blocks/src/MediaBlock/MediaBlock.test.tsx
packages/blocks/src/Navigation/Navigation.test.tsx
packages/blocks/src/Quote/Quote.test.tsx
packages/blocks/src/Testimonial/Testimonial.test.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-974

[COM-974] Fix @cmpsr/blocks build

---

.changeset/proud-schools-sparkle.md
packages/signalwire/.swcrc

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-974

[COM-974] Fix @cmpsr/signalwire/client package build

---

.changeset/dirty-years-flow.md
.changeset/moody-coats-bow.md
packages/components/src/theme/ComposerProvider/ComposerProvider.tsx
packages/components/src/theme/ComposerTheme/breakpoints.ts
packages/components/src/theme/ComposerTheme/theme.ts
projects/ui-storybook/.storybook/preview.tsx

Define default breakpoints

---

.changeset/cool-ties-repair.md
.changeset/heavy-flowers-wave.md
packages/signalwire/src/VideoChat/components/Login/Login.stories.tsx
packages/signalwire/src/VideoChat/components/Login/Login.tsx
projects/ui-storybook/.storybook/main.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-981

[COM-981] Show composer rooms logo from contentful

---

.github/workflows/deploy_storybook.yml

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-982

[COM-982] Fix storybook deploy

---

.changeset/lazy-chicken-dress.md
packages/blocks/src/Hero/Hero.stories.tsx
packages/blocks/src/Hero/Hero.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-971

[COM-971] Remove textTransform uppercase of Hero.Overline

---

.changeset/chilly-dodos-admire.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

Fix multiple styling

---

.changeset/lazy-tables-shout.md
packages/blocks/src/Testimonial/Testimonial.stories.tsx
packages/blocks/src/Testimonial/Testimonial.test.tsx
packages/blocks/src/Testimonial/Testimonial.tsx
packages/blocks/src/Testimonial/types.ts

Simplify testimonial author

---

.changeset/calm-eggs-pretend.md
packages/blocks/src/Navigation/components/NavigationLinks.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-990

[COM-990] Add spacing between navigation links when there are no dividers

---

.changeset/modern-cooks-bathe.md
packages/blocks/src/Hero/Hero.stories.tsx
packages/blocks/src/Hero/Hero.tsx

Remove default maxWidth and width of Hero.Content and Hero.Image

---

.changeset/green-bees-study.md
packages/components/src/theme/ComposerTheme/Components/Button.ts
packages/components/src/theme/ComposerTheme/Components/Link.ts

Fix Button border radius

---

.changeset/nine-onions-explain.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1059

[COM-1059] Allow anything but : in prop name

---

.changeset/olive-drinks-film.md
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1059

[COM-1059] Do not capture open bracket in prop name

---

.changeset/pretty-ladybugs-pretend.md
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.test.ts
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-784

[COM-784] Add support for AccordionsGallery fieldType

---

.changeset/tricky-elephants-stare.md
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.test.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.ts

Prefix slugs with a slash

---

.changeset/mean-goats-pump.md
package.json
packages/components/src/components/overlay/Tooltip/Tooltip.stories.tsx
yarn.lock

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-723
* Updates chromatic to latest version 6.17.0 (from v5)

COM-723 Updates chromatic to latest + Tooltip story fix

---

.changeset/fluffy-dragons-melt.md
.github/workflows/delete_storybook.yml

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-1167

COM-1167 CI: Fixes delete-storybook github action

---

.changeset/tame-baboons-thank.md
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.test.ts
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.ts

This PR should be merged before this one (https://github.com/cmpsr/auto-tune/pull/128), since it depends on this one
**Checklist**
[COM-1141](https://impulsumvc.atlassian.net/browse/COM-1141?atlOrigin=eyJpIjoiMGZjZGFiN2MwODE4NDIxNjg5NWNmYzk4ZTQ2YjRlMTMiLCJwIjoiaiJ9)
[COM-1141]: https://impulsumvc.atlassian.net/browse/COM-1141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added new FieldType for Tag Empty Container (COM-1141)

---

.changeset/good-rocks-teach.md
packages/blocks/package.json
packages/signalwire/package.json

[chore] Align Versions

---

.changeset/tasty-baboons-roll.md
packages/nextjs-contentful-renderer/package.json

Fix - nextjs-contentful-renderer

---

.changeset/eleven-cobras-sing.md
packages/carousel/.gitignore
packages/carousel/.swcrc
packages/carousel/README.md
packages/carousel/jest.config.js
packages/carousel/package.json
packages/carousel/src/Carousel/Carousel.stories.tsx
packages/carousel/src/Carousel/Carousel.test.tsx
packages/carousel/src/Carousel/Carousel.tsx
packages/carousel/src/Carousel/index.ts
packages/carousel/src/Carousel/types.ts
packages/carousel/src/index.ts
packages/carousel/src/tests/renderWithProviders.tsx
packages/carousel/tsconfig.json
projects/ui-storybook/.storybook/main.ts
projects/ui-storybook/.storybook/preview.tsx
projects/ui-storybook/package.json
yarn.lock

**Checklist**
https://impulsumvc.atlassian.net/browse/HAM-65

[HAM-65] Create Carousel package

---

.changeset/red-fireants-lie.md
packages/carousel/client/index.d.ts
packages/carousel/client/index.js
packages/carousel/client/package.json
packages/nextjs-contentful-renderer/package.json
packages/nextjs-contentful-renderer/src/MdxRenderer/MdxRenderer.tsx

Update @cmpsr/carousel to optional in @cmpsr/nextjs-contentful-renderer

---

.changeset/proud-beds-watch.md
.changeset/red-fireants-lie.md
packages/carousel/client/index.d.ts
packages/carousel/client/index.js
packages/carousel/client/package.json
packages/nextjs-contentful-renderer/package.json
packages/nextjs-contentful-renderer/src/MdxRenderer/MdxRenderer.tsx

Revert "Update @cmpsr/carousel to optional in @cmpsr/nextjs-contentful-renderer"

---

package.json
yarn.lock

https://impulsumvc.atlassian.net/browse/COM-1259

[COM-1259] Update lerna and turbo to latest versions to fix security issues

---

.changeset/dry-clouds-appear.md
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.test.ts
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.ts

Add support for Carousel field type in CML

---

.changeset/fifty-laws-turn.md
packages/carousel/src/Carousel/Carousel.stories.tsx
packages/carousel/src/Carousel/Carousel.tsx
packages/carousel/src/Carousel/types.ts

Wrap Carousel Slide in Flex element and add default margin

---

.changeset/pink-seals-jam.md
packages/nextjs-contentful-renderer/src/getPageContent/getPageContent.test.ts
packages/nextjs-contentful-renderer/src/getPageContent/getPageContent.ts
packages/nextjs-contentful-renderer/src/getStaticPageContent/getStaticPageContent.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/types.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/types.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/getPageById.test.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/getPageById.ts

Replica: Meta Configuration

---

.changeset/chilly-kids-punch.md
packages/nextjs-contentful-renderer/src/utils/getPageById/getPageById.test.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/getPageById.ts

Fix: Replica Meta

---

.changeset/hip-papayas-give.md
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/types.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/getPageById.test.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/getPageById.ts

**Checklist**
- Adds `title` to `Replica`

Replica: Title

---

.changeset/nice-countries-sit.md
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.ts

fix: Replica data returned

---

.changeset/pink-parents-grin.md
packages/components/src/components/form/Button/Button.tsx
packages/components/src/components/form/Button/types.ts
packages/components/src/theme/ComposerTheme/Components/Button.ts

feat: support size/variant properties as responsive values

---

.changeset/big-pumpkins-check.md
packages/nextjs-contentful-renderer/src/utils/contentful/getStaticRoutes/getStaticRoutes.ts

Feature: Static Replicas

---

.changeset/thin-experts-smash.md
packages/components/src/components/dataDisplay/OrderedList/OrderedList.stories.tsx
packages/components/src/components/dataDisplay/OrderedList/OrderedList.tsx
packages/components/src/components/dataDisplay/OrderedList/index.ts
packages/components/src/components/dataDisplay/OrderedList/types.ts
packages/components/src/components/dataDisplay/UnorderedList/UnorderedList.stories.tsx
packages/components/src/components/dataDisplay/UnorderedList/UnorderedList.tsx
packages/components/src/components/dataDisplay/UnorderedList/types.ts
packages/components/src/components/dataDisplay/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1278

[COM-1278] Add OrderedList component

---

.changeset/metal-tigers-report.md
packages/nextjs-contentful-renderer/src/MdxRenderer/MarkdownContext/MarkdownContext.tsx
packages/nextjs-contentful-renderer/src/MdxRenderer/MarkdownContext/index.ts
packages/nextjs-contentful-renderer/src/MdxRenderer/MdxRenderer.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1279

Com 1279 markdown fixes

---

.changeset/hungry-comics-sparkle.md
packages/components/src/components/dataDisplay/UnorderedList/types.ts

We need this in order to use it in the nextjs-renderer package for customising list items.
**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1292

[COM-1292] Export ListItemProps

---

.changeset/witty-hounds-collect.md
packages/nextjs-contentful-renderer/src/MdxRenderer/MarkdownContext/MarkdownContext.tsx
packages/nextjs-contentful-renderer/src/MdxRenderer/MarkdownContext/types.ts
packages/nextjs-contentful-renderer/src/MdxRenderer/MdxRenderer.tsx
packages/nextjs-contentful-renderer/src/MdxRenderer/components/components.ts
packages/nextjs-contentful-renderer/src/MdxRenderer/components/index.ts
packages/nextjs-contentful-renderer/src/MdxRenderer/renderers/index.ts
packages/nextjs-contentful-renderer/src/MdxRenderer/renderers/link.tsx
packages/nextjs-contentful-renderer/src/MdxRenderer/renderers/list.tsx
packages/nextjs-contentful-renderer/src/MdxRenderer/renderers/text.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1292

COM-1292 li styling

---

.changeset/long-ghosts-rule.md
packages/components/src/components/form/Checkbox/Checkbox.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1294

[COM-1294] Export Checkbox component as a forwardRef

---

.changeset/light-rockets-visit.md
packages/components/src/components/form/Input/Input.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1293

[COM-1293] Export Input component as a forwardRef

---

.changeset/breezy-comics-smile.md
packages/components/src/components/overlay/Dropdown/Dropdown.stories.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1180

[COM-1180] Add with icons story to Dropdown

---

package.json
yarn.lock

[no-release] Update lerna to latest version

---

.changeset/config.json
.github/workflows/changeset-publish-canary.yml
.github/workflows/delete-old-prereleases.yml
package.json
yarn.lock

Release canaries on PR labeled

---

.changeset/hot-ants-care.md
packages/nextjs-contentful-renderer/README.md
packages/nextjs-contentful-renderer/package.json
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.test.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/getPageById.test.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/getPageById.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getPageById/types.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/getRouteBySlug.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getRouteBySlug/types.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/getPageById.test.ts
packages/nextjs-contentful-renderer/src/utils/getPageById/getPageById.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1317
We are adding a couple of new fields to the `Page` and `Replica` content models in contentful. In order to update to this new version those fields will have to be added to the contentful project first.

[COM-1317] CML global variables

---

.changeset/neat-radios-deny.md
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.test.ts
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/HAM-362
- No breaking change

feat(HAM-362) configures json cml placeholder replacement

---

.changeset/silver-planes-brake.md
packages/nextjs-contentful-renderer/src/utils/contentful/getStaticRoutes/getStaticRoutes.test.ts
packages/nextjs-contentful-renderer/src/utils/contentful/getStaticRoutes/getStaticRoutes.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/HAM-389

[HAM-389] Retrieve all slugs recursively 

---

.changeset/tiny-worms-decide.md
packages/analytics/src/integrations/ga/GA.ts
packages/analytics/src/integrations/gtag/GTag.ts

Update gtag methods

---

.changeset/happy-teachers-hear.md
packages/blocks/src/Footer/index.ts

Export footer types

---

.changeset/selfish-sheep-add.md
packages/components/src/components/navigation/Breadcrumb/Breadcrumb.tsx

Breadcrumb last child should use body medium typography

---

.changeset/orange-socks-mix.md
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.test.ts
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.ts

Update replaceCmlPlaceholders to replace default boolean values

---

.changeset/tender-falcons-attend.md
package.json
packages/blocks/src/Navigation/Navigation.stories.tsx
packages/blocks/src/Navigation/Navigation.tsx
packages/blocks/src/Navigation/components/NavigationActions.tsx
packages/blocks/src/Navigation/components/NavigationContext.ts
packages/blocks/src/Navigation/components/NavigationLinks.tsx
packages/blocks/src/Navigation/types.ts

Updates navigation to:
- allow positioning links to the end
- allow keeping action links always visible on the
**Checklist**
- https://5eed577398d08d0022b52d76-wenxzcwsoq.chromatic.com/?path=/story/blocks-navigation--playground

feat: updates navigation to allow keeping action links always visible on the navbar and position links to the end 

---

.changeset/five-singers-trade.md
packages/blocks/src/Navigation/components/NavigationLinks.tsx

This is a small patch for this other PR
- https://github.com/cmpsr/composer/pull/770
**Checklist**

fix: prevents navigation logo from shrinking

---

.changeset/seven-weeks-return.md
packages/blocks/src/Navigation/components/NavigationLinks.tsx

fix(HAM-443) allow nav link color to be set via variant prop

---

.changeset/fresh-chairs-glow.md
packages/components/scripts/generate_icons.js
packages/components/src/components/media/Icons/Icons.stories.tsx
packages/components/src/components/media/Icons/Icons.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1320

[COM-1320] Add IconListNumbers

---

.changeset/quiet-birds-care.md
packages/components/src/components/navigation/index.ts

Export stepper

---

.changeset/cool-bugs-yell.md
packages/components/src/theme/ComposerTheme/Components/Input.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1373

[COM-1373] Update Input height to match design

---

.changeset/large-pillows-sniff.md
packages/markdown-editor/src/MarkdownEditor/MarkdownEditor.test.tsx
packages/markdown-editor/src/MarkdownEditor/MarkdownEditor.tsx
packages/markdown-editor/src/MarkdownEditor/plugins/ToolbarPlugin/ToolbarPlugin.tsx
packages/markdown-editor/src/MarkdownEditor/plugins/ToolbarPlugin/types.ts
packages/markdown-editor/src/MarkdownEditor/types.ts

**Subsequent autotune [PR](https://github.com/cmpsr/auto-tune/pull/193)**
**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1377

[COM-1337] Support external actions in toolbar and customisation of container, content and content editable elements

---

.changeset/late-schools-know.md
packages/components/src/theme/ComposerTheme/Components/Input.ts
packages/components/src/theme/ComposerTheme/Components/NumberInput.ts
packages/components/src/theme/ComposerTheme/Components/Select.ts
packages/components/src/theme/ComposerTheme/Components/Textarea.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1388

[COM-1388] Update Inputs placeholder color token

---

.changeset/poor-bikes-perform.md
packages/components/src/components/form/Checkbox/Checkbox.stories.tsx
packages/components/src/theme/ComposerTheme/Components/Checkbox.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1398

[COM-1398] Checkbox alignment

---

.changeset/calm-shirts-drive.md
.changeset/tough-foxes-relate.md
package.json
packages/cloud-logger/src/index.test.ts
packages/cloud-storage/src/index.test.ts
packages/components/package.json
packages/contentful-core/src/renderers/renderFromContentfulModel.test.tsx
yarn.lock

**Checklist**
**Other information**
- Bumps chakra-ui to the latest version
- Bumps jest and related packages as required for tests failings after bumping chakra-ui

Upgrade dependencies

---

.changeset/lemon-penguins-promise.md
packages/components/src/components/dataDisplay/Tag/types.ts
packages/components/src/components/feedback/ProgressBar/types.ts
packages/components/src/components/feedback/Spinner/types.ts
packages/components/src/components/form/Autocomplete/types.ts
packages/components/src/components/form/Checkbox/types.ts
packages/components/src/components/form/IconButton/types.ts
packages/components/src/components/form/Input/types.ts
packages/components/src/components/form/NumberInput/types.ts
packages/components/src/components/form/PinInput/types.ts
packages/components/src/components/form/Radio/types.ts
packages/components/src/components/form/Select/types.ts
packages/components/src/components/form/Switch/types.ts
packages/components/src/components/form/Textarea/types.ts
packages/components/src/components/media/Avatar/types.ts
packages/components/src/components/media/Icons/types.ts
packages/components/src/components/navigation/Link/Link.tsx
packages/components/src/components/navigation/Link/getIconSize/getIconSize.test.ts
packages/components/src/components/navigation/Link/getIconSize/getIconSize.ts
packages/components/src/components/navigation/Link/getIconSize/index.ts
packages/components/src/components/navigation/Link/types.ts
packages/components/src/components/other/CloseButton/types.ts
packages/components/src/components/overlay/Modal/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1401

[COM-1401] Make size and variant responsive values

---

.changeset/flat-kings-draw.md
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.test.ts
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.ts
packages/cml/src/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1397

[COM-1397] Add support for strings field type

---

.changeset/ninety-geckos-roll.md
packages/carousel/src/Carousel/Carousel.stories.tsx
packages/carousel/src/Carousel/Carousel.test.tsx
packages/carousel/src/Carousel/Carousel.tsx
packages/carousel/src/Carousel/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1324

[COM-1324] Adapt Carousel to use composition

---

.changeset/quick-seas-pay.md
packages/components/scripts/generate_icons.js
packages/components/src/components/media/Icons/Icons.stories.tsx
packages/components/src/components/media/Icons/Icons.tsx
packages/markdown-editor/src/MarkdownEditor/MarkdownEditor.stories.tsx
packages/markdown-editor/src/MarkdownEditor/MarkdownEditor.test.tsx
packages/markdown-editor/src/MarkdownEditor/MarkdownEditor.tsx
packages/markdown-editor/src/MarkdownEditor/constants.ts
packages/markdown-editor/src/MarkdownEditor/plugins/SetInitialValuePlugin/SetInitialValuePlugin.test.tsx
packages/markdown-editor/src/MarkdownEditor/plugins/SetInitialValuePlugin/SetInitialValuePlugin.tsx
packages/markdown-editor/src/MarkdownEditor/plugins/SetInitialValuePlugin/types.ts
packages/markdown-editor/src/MarkdownEditor/plugins/ToolbarPlugin/ToolbarPlugin.tsx
packages/markdown-editor/src/MarkdownEditor/plugins/ToolbarPlugin/types.ts
packages/markdown-editor/src/MarkdownEditor/types.ts

**Checklist**
https://5eed577398d08d0022b52d76-howjxnpmqu.chromatic.com/?path=/story/components-editors-markdowneditor--plain-editor-mode

feat(COM-1376) adds markdown view toggle button to markdown editor

---

.changeset/loud-kids-laugh.md
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.test.ts
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.ts
packages/cml/src/types.ts

[AUTO-TUNE PR](https://github.com/cmpsr/auto-tune/pull/207)
**Checklist**

Update strings replacement to consider null and undefined scenarios

---

.github/workflows/changeset-publish-canary.yml
.github/workflows/chromatic.yml
.github/workflows/linter.yml
.github/workflows/publish.yml
.github/workflows/test.yml
package.json
yarn.lock

Remove lerna from dependencies

---

.changeset/swift-walls-begin.md
packages/carousel/src/Carousel/Carousel.stories.tsx
packages/components/src/components/navigation/Link/types.ts
packages/components/src/theme/ComposerTheme/Colors/colors.ts
packages/components/src/theme/ComposerTheme/Components/Link.ts
packages/components/src/theme/ComposerTheme/Components/Tabs.ts
packages/components/src/theme/ComposerTheme/Components/Textarea.ts

**Checklist**
- [Update tab](https://impulsumvc.atlassian.net/browse/COM-1413)
- [Update disabled text color](https://impulsumvc.atlassian.net/browse/COM-1414)
- [Textarea disabled input filled](https://impulsumvc.atlassian.net/browse/COM-1415)
- [Textarea disabled input flushed filled](https://impulsumvc.atlassian.net/browse/COM-1416)
- [Add destroy link variant](https://impulsumvc.atlassian.net/browse/COM-1440)

[COM-1413/COM-1414/COM-1415/COM-1416/COM-1419/COM-1440] Composer improvements

---

.changeset/pink-fireants-develop.md
packages/markdown-editor/src/MarkdownEditor/plugins/FloatingLinkEditorPlugin/FloatingLinkEditorPlugin.tsx
packages/markdown-editor/src/MarkdownEditor/utils/useEditorFocus.tsx

**Checklist**
https://impulsumvc.atlassian.net/browse/HAM-639

[HAM-639] FloatingLink shouldn't be shown when editor is not focused

---

.changeset/itchy-peas-applaud.md
packages/nextjs-contentful-renderer/src/MdxRenderer/renderers/link.tsx

[COM-1442] Update anchor rendered in MDX to use inline display mode

---

.changeset/good-islands-hang.md
packages/components/src/components/form/Radio/index.ts

Re-export RadioGroup from @chakra-ui

---

.changeset/fifty-cherries-admire.md
.github/dependabot.yml
packages/analytics/package.json
packages/cloud-kms/package.json
packages/cloud-logger/package.json
packages/cloud-storage/package.json
packages/firebase-dynamic-link/package.json
packages/firestore/package.json
packages/plaid-link/package.json
packages/plaid/package.json
packages/signalwire/package.json
packages/twilio/package.json
yarn.lock

**Checklist**
- Move rimraf to devDependencies

Update rimraf to latest version

---

.changeset/hot-moons-bow.md
packages/components/src/index.ts
packages/components/src/theme/ComposerTheme/Components/Input.ts
packages/components/src/theme/ComposerTheme/Components/NumberInput.ts
packages/components/src/theme/ComposerTheme/Components/Select.ts

Re-export @chakra-ui/react transitions

---

.changeset/fuzzy-sloths-trade.md
packages/components/src/components/overlay/Popover/Popover.stories.tsx
packages/components/src/components/overlay/Popover/Popover.test.tsx
packages/components/src/components/overlay/Popover/Popover.tsx
packages/components/src/components/overlay/Popover/index.ts
packages/components/src/components/overlay/Popover/types.ts
packages/components/src/components/overlay/index.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1478

[COM-1478] Popover

---

.changeset/eight-eggs-own.md
.github/workflows/changeset-publish-canary.yml
.github/workflows/chromatic.yml
.github/workflows/linter.yml
.github/workflows/publish.yml
.github/workflows/test.yml
packages/twilio/src/conversations/TwilioConversation.ts
packages/twilio/src/index.ts
packages/twilio/src/sms/TwilioSms.ts
packages/twilio/src/sms/index.test.ts
packages/twilio/src/types/ChatMessage.ts
packages/twilio/src/types/TwilioConversation.ts
packages/twilio/src/types/index.ts
packages/twilio/src/verification/TwilioVerification.test.ts
packages/twilio/src/verification/TwilioVerification.ts
packages/twilio/src/verification/index.test.ts
packages/twilio/src/verification/index.ts

[DM-536] Add support for twilio verification 

---

.changeset/nervous-jars-learn.md
packages/components/src/theme/ComposerTheme/Components/Select.ts

Update Select field to use proper focus styles on focus

---

.changeset/polite-monkeys-mate.md
packages/components/src/theme/ComposerTheme/Components/Select.ts

Update Select field to use proper focus styles on focus (Flushed variant)

---

.changeset/stupid-lies-beg.md
packages/blocks/package.json
packages/carousel/package.json
packages/markdown-editor/package.json
packages/nextjs-contentful-renderer/package.json
packages/signalwire/package.json

chore: bump peerDeps to latest dep version

---

.changeset/lemon-bobcats-itch.md
packages/components/src/components/form/Button/Button.tsx

Update `size` passed to obtain `loading` styles to use `responsiveSize`

---

.changeset/early-brooms-lie.md
.eslintrc.js
packages/markdown-editor/src/MarkdownEditor/themes/defaultTheme.ts
packages/nextjs-contentful-renderer/src/generateMdx/generateMdx.ts
packages/signalwire/src/sms/SignalwireSms.ts
packages/signalwire/src/types/ClientConfig.ts

**Checklist**
- Added multiline desired behaviour to linter config

Improve linter config

---

.changeset/pretty-balloons-grab.md
packages/components/src/components/navigation/Link/Link.tsx
packages/components/src/components/navigation/Link/getIconSize/getIconSize.test.ts
packages/components/src/components/navigation/Link/getIconSize/getIconSize.ts
packages/components/src/components/navigation/Link/getIconSize/index.ts

Revert `getIconSize` removal in `Link`

---

.changeset/ninety-toys-sneeze.md
packages/components/src/components/dataDisplay/NumberedList/types.ts

fix: Fix the imports in the NumberedList type

---

.changeset/wicked-books-rest.md
projects/ui-storybook/.storybook/main.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://impulsumvc.atlassian.net/browse/COM-1551

[COM-1551] Build stories as JSON

---

.changeset/lucky-seas-dream.md
packages/components/package.json

**Other information**: Allows the installation script to work on Windows machines running Git Bash / WSL

fix: Update gen:theme-typings script OS portable

---

.changeset/rich-planets-boil.md
packages/components/src/components/form/Slider/Slider.stories.tsx
packages/components/src/theme/ComposerTheme/Components/Slider.ts

**Checklist**
**What is the ticket / issue associated with this change?** (https://impulsumvc.atlassian.net/browse/COM-1557)

[COM-1557] Update the slider with disabled styles

---

.changeset/hungry-rules-leave.md
packages/components/src/theme/ComposerTheme/Components/Button.ts

**Checklist**
**What is the ticket / issue associated with this change?** ([ticket](https://impulsumvc.atlassian.net/browse/COM-1592))

[COM-1592] Update theme Button colors

---

.changeset/fluffy-crews-vanish.md
.changeset/tricky-students-dream.md
packages/components/src/theme/ComposerTheme/Colors/colors.ts
packages/components/src/theme/ComposerTheme/Components/Badge.ts

**Checklist**
**What is the ticket / issue associated with this change?** ([Link to the ticket or issue](https://impulsumvc.atlassian.net/browse/COM-1591))
**Does this PR introduce a breaking change?** No
**Storybook Link** ([Link to a local storybook](https://5eed577398d08d0022b52d76-djypusrkbu.chromatic.com/))

[COM-1591] Add new color token 'text-inform' and update Badge component styles

---

.changeset/stupid-doors-wait.md
packages/components/src/components/form/ButtonIcon/ButtonIcon.stories.tsx
packages/components/src/components/form/ButtonIcon/ButtonIcon.tsx
packages/components/src/theme/ComposerTheme/Components/ButtonIcon.ts
packages/components/src/theme/ComposerTheme/Spacing/spacing.ts

**Checklist**
**What is the ticket / issue associated with this change?** ([ticket](https://impulsumvc.atlassian.net/browse/COM-1597) or issue)

[COM-1597] Update Icon Button - Tokens on paddings

---

.changeset/friendly-jeans-marry.md
packages/components/src/components/feedback/Toast/useToast.test.tsx
packages/components/src/components/feedback/Toast/useToast.tsx

**Checklist**
**What is the ticket / issue associated with this change?** 
https://impulsumvc.atlassian.net/browse/COM-1677
**Screenshots**

[COM-1677] Fix toast text overlapping with the close button

---

.changeset/calm-rabbits-bathe.md
packages/components/src/components/dataDisplay/Tag/Tag.stories.tsx
packages/components/src/components/dataDisplay/Tag/Tag.tsx
packages/components/src/components/dataDisplay/Tag/types.ts
packages/components/src/components/form/SegmentedButton/SegmentedButton.tsx
packages/components/src/theme/ComposerTheme/Components/Tag.ts
packages/components/src/theme/ComposerTheme/Spacing/spacing.ts

**Checklist**
**What is the ticket / issue associated with this change?** ([Link to the ticket](https://impulsumvc.atlassian.net/browse/COM-1682))
**Storybook Link** ([Link](https://5eed577398d08d0022b52d76-njimhjimib.chromatic.com/))

[COM-1682] Tag update

---

.changeset/orange-comics-sneeze.md
packages/components/src/components/form/AutocompleteMultiSelect/AutocompleteMultiSelect.tsx
packages/components/src/components/form/AutocompleteMultiSelect/AutocompleteMultiSelectList.tsx
packages/components/src/components/form/AutocompleteMultiSelect/AutocompleteMultiSelectSelectedItems.tsx
packages/components/src/components/form/AutocompleteMultiSelect/types.ts

Update `AutocompleteMultiSelect` to use internal controlled actions

---

.changeset/bright-mugs-applaud.md
packages/components/src/components/form/Textarea/Textarea.tsx

Update `Textarea` to use `forwardRef`

---

.changeset/pink-taxis-judge.md
packages/analytics/src/AnalyticsProvider.tsx
packages/analytics/src/integrations/amplitude/Amplitude.test.ts
packages/analytics/src/integrations/amplitude/Amplitude.ts
packages/analytics/src/integrations/amplitude/index.ts
packages/analytics/src/integrations/amplitude/loadAmplitude.ts
packages/analytics/src/integrations/amplitude/types.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1684

[COM-1684] Add support for amplitude analytics

---

.changeset/itchy-vans-dance.md
packages/analytics/src/integrations/amplitude/Amplitude.test.ts
packages/analytics/src/integrations/amplitude/Amplitude.ts

**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1706

[COM-1706] Add user traits to amplify identify integration

---

.changeset/brown-frogs-suffer.md
packages/components/src/components/layouts/Grid/Grid.tsx

**Checklist**
**What is the ticket / issue associated with this change?** none
**Does this PR introduce a breaking change?** no
**Storybook Link** [(Link to a local storybook url to review new functionality)](http://localhost:8080/?path=/story/components-layouts-grid--playground)

feat: add forwardRef to the Grid component

---

.changeset/proud-emus-accept.md
packages/components/src/theme/ComposerTheme/Components/Accordion.ts

chore: update accordion divider color

---

.changeset/calm-chefs-give.md
packages/analytics/src/AnalyticsContext.ts
packages/analytics/src/AnalyticsProvider.tsx
packages/analytics/src/integrations/amplitude/Amplitude.test.ts
packages/analytics/src/integrations/amplitude/Amplitude.ts
packages/analytics/src/integrations/ga/GA.ts
packages/analytics/src/integrations/gtag/GTag.ts
packages/analytics/src/integrations/segment/Segment.ts
packages/analytics/src/integrations/types.ts
packages/analytics/src/types.ts

**Checklist**
**What is the ticket / issue associated with this change?** Amplitude revenue functions

feat: add revenue to amplitude integration

---

.changeset/two-eggs-tell.md
packages/components/src/components/dataDisplay/Badge/index.ts

Fix export Badge types

---

.changeset/twelve-laws-sort.md
packages/components/scripts/generate_icons.js
packages/components/src/components/media/Icons/Icons.stories.tsx
packages/components/src/components/media/Icons/Icons.tsx

**Checklist**
**What is the ticket / issue associated with this change?** [(Link to the ticket or issue)](https://impulsumvc.atlassian.net/browse/COM-1730)

feat: add new icon dots vertical

---

.changeset/quick-carrots-double.md
packages/components/src/theme/ComposerTheme/Components/Button.ts
packages/components/src/theme/ComposerTheme/Components/Link.ts

feat: Button, Link - use focusVisible instead of focus styles. Hover styles only on desktop devices.

---

.changeset/wicked-maps-shop.md
packages/components/src/theme/ComposerTheme/Components/Button.ts

fix: Button - Ghost variant hover style

---

.changeset/yellow-doors-raise.md
packages/components/src/components/feedback/ProgressBar/ProgressBar.stories.tsx
packages/components/src/components/feedback/ProgressBar/types.ts
packages/components/src/theme/ComposerTheme/Components/ProgressBar.ts
packages/components/src/theme/ComposerTheme/Radius/radius.ts

**Checklist**
**Storybook [Link](https://5eed577398d08d0022b52d76-mfpeinufnv.chromatic.com/)**

[COM-1743] Update ProgressBar component styles

---

.changeset/five-beers-repair.md
packages/components/src/theme/ComposerTheme/Components/Tooltip.ts
packages/components/src/theme/ComposerTheme/Radius/radius.ts
packages/components/src/theme/ComposerTheme/Shadows/shadows.ts
packages/components/src/theme/ComposerTheme/Spacing/spacing.ts

Refactor the tooltip component to update its styling.
- Update padding tokens.
- Update border radius token.
- Add new box-shadow token.
**Checklist**
**What is the ticket / issue associated with this change?** ([ticket](https://impulsumvc.atlassian.net/jira/software/c/projects/COM/boards/20/backlog?assignee=712020%3Ae9794bf2-2a1d-46c4-8af0-86b929c8e8ec&selectedIssue=COM-1745))
**Storybook Link** ([Link](https://5eed577398d08d0022b52d76-lavpubkqsy.chromatic.com/?path=/story/components-overlay-tooltip--all))

[COM-1745] Update tooltip tokens

---

.changeset/happy-gorillas-breathe.md
packages/components/src/theme/ComposerTheme/Components/ButtonIcon.ts
packages/components/src/theme/ComposerTheme/Radius/radius.ts

**Checklist**
**What is the ticket / issue associated with this change?** ([Link](https://impulsumvc.atlassian.net/jira/software/c/projects/COM/boards/20/backlog?assignee=712020%3Ae9794bf2-2a1d-46c4-8af0-86b929c8e8ec&selectedIssue=COM-1750))
**Storybook Link** ([Link](https://5eed577398d08d0022b52d76-dbmuwnivjn.chromatic.com/?path=/story/components-form-buttonicon--all))

[COM-1750] Add radii-button-icon token

---

.changeset/chatty-toes-hammer.md
packages/components/src/theme/ComposerTheme/Colors/colors.ts
packages/components/src/theme/ComposerTheme/Components/CloseButton.ts

**Checklist**
**What is the ticket / issue associated with this change?** ([Ticket](https://impulsumvc.atlassian.net/jira/software/c/projects/COM/boards/20/backlog?assignee=712020%3Ae9794bf2-2a1d-46c4-8af0-86b929c8e8ec&selectedIssue=COM-1748))
**Storybook Link** ([Link](https://5eed577398d08d0022b52d76-zkrsbkdbkl.chromatic.com/?path=/story/components-other-closebutton--all))

[COM-1748] Update CloseButton color tokens

---

.changeset/twenty-mugs-crash.md
packages/components/src/theme/ComposerTheme/Colors/colors.ts
packages/components/src/theme/ComposerTheme/Components/Input.ts
packages/components/src/theme/ComposerTheme/Radius/radius.ts

**Checklist**
**What is the ticket / issue associated with this change?** ([ticket](https://impulsumvc.atlassian.net/jira/software/c/projects/COM/boards/20/backlog?assignee=712020%3Ae9794bf2-2a1d-46c4-8af0-86b929c8e8ec&selectedIssue=COM-1747))
**Storybook Link** ([Link](https://5eed577398d08d0022b52d76-ecyzswdeth.chromatic.com/?path=/story/components-form-input--all))

[COM-1323] Add new hover and focus color tokens and new border-radius token

---

.changeset/spicy-dodos-accept.md
packages/components/src/theme/ComposerTheme/Components/Radio.ts

**Checklist**
**What is the ticket / issue associated with this change?** ([Link](https://impulsumvc.atlassian.net/browse/COM-1757))
**Storybook Link** ([Link](https://5eed577398d08d0022b52d76-dlacicdvdb.chromatic.com/))

[COM 1757] Radio update

---

.changeset/ninety-knives-exist.md
packages/components/src/components/form/SegmentedButton/SegmentedButton.test.tsx
packages/components/src/components/form/SegmentedButton/SegmentedButton.tsx
packages/components/src/components/form/SegmentedButton/types.ts

Refactor SegmentedButton component to lift the state

---

.changeset/early-doors-confess.md
packages/analytics/src/integrations/gtag/GTag.ts
packages/analytics/src/integrations/gtag/Gtag.test.ts

**Checklist**
**What is the ticket / issue associated with this change?** Catch request
**Does this PR introduce a breaking change?** Gtag implementations that call revenue function will send data now

Composer gtag revenue

---

.changeset/red-dancers-march.md
packages/analytics/package.json
packages/analytics/src/AnalyticsProvider.test.tsx
packages/analytics/src/AnalyticsProvider.tsx
packages/analytics/src/integrations/amplitude/Amplitude.test.ts
packages/analytics/src/integrations/amplitude/Amplitude.ts
packages/analytics/src/integrations/amplitude/types.ts
packages/analytics/src/integrations/index.ts

**Checklist**
**What is the ticket / issue associated with this change?** https://linear.app/catchbio/issue/ENG-466/resolve-event-and-user-property-ambiguity-in-our-product-analytics
**Does this PR introduce a breaking change?** amplitude revenue event stops working. As required by the ticket.

Composer amplitude revenue event
