cmpsr/composer

.changeset/kind-chicken-appear.md
packages/analytics/.babelrc
packages/analytics/lib/index.test.js
packages/analytics/lib/integrations/ga/GA.js
packages/analytics/lib/integrations/segment/Segment.js
packages/analytics/package.json
yarn.lock

**Checklist**
There was an issue causing the package to crash when was compiled. Following code was generating the crash when compiled:
```
identify: Identify = (userId, traits) => {
(window as any).analytics(userId, traits);
}
```
Not crashing
```
identify(userId, traits) {
(window as any).analytics(userId, traits);
}
```
Solved adding a class property babel [plugin](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) to compile these class methods.

Add babel plugin to compile class properties

---

.changeset/strange-parents-watch.md
packages/contentful-core/package.json
packages/contentful-core/src/client/createContentfulLink.ts
yarn.lock

**Checklist**
Next.js includes fetch by default, however other stacks do not. Adding `cross-fetch` provides a cross-platform fetch option. 
In a future PR we may want to check for the existence of `fetch` before importing.

Add cross-fetch for non-Next applications

---

.changeset/tender-jars-agree.md
packages/contentful-core/src/components/ComponentRenderer/ComponentRenderer.tsx
packages/contentful-core/src/renderers/renderFromContentfulModel.tsx

**Checklist**
@ryanhefner - A couple of tiny tweaks here. The first is to allow the context to be null, in situations where we simply want the `ComponentRenderer` without any `Context`. 
The second is to pass `componentMap` to the components themselves, as there are situations where components also want to reference `ComponentRenderer` and lose the overrides at the top level.

ComponentMap flexibility

---

.changeset/short-bulldogs-dream.md
packages/contentful-core/src/components/ComponentRenderer/ComponentRenderer.tsx
packages/contentful-core/src/components/ComponentRendererWithContext/ComponentRendererWithContext.tsx
packages/contentful-core/src/components/ComponentRendererWithQuery/ComponentRendererWithQuery.tsx

**Checklist**
Added `className` as a prop to ComponentRenderer helpers to ensure that `styled-components` and other CSS-in-JS can pass through custom styling down through the tree.

feat: Add classname to ComponentRenderers

---

packages/styled-components/src/components/primitives/Link/Link.stories.tsx
packages/styled-components/src/components/primitives/Link/Link.styled.ts
packages/styled-components/src/components/primitives/Link/Link.test.tsx
packages/styled-components/src/components/primitives/Link/Link.tsx
packages/styled-components/src/components/primitives/Link/Link.types.ts
packages/styled-components/src/components/primitives/Link/index.ts
packages/styled-components/src/components/primitives/index.ts

Styled Link

---

packages/styled-components/src/components/Components.types.ts
packages/styled-components/src/components/primitives/Form/ExpandableTextFieldIcon/ExpandableTextFieldIcon.tsx
packages/styled-components/src/components/primitives/Form/ExpandableTextFieldIcon/ExpandableTextFieldIcon.types.ts
packages/styled-components/src/components/primitives/Form/SearchField/SearchField.tsx
packages/styled-components/src/components/primitives/Form/SearchField/SearchField.types.ts
packages/styled-components/src/components/primitives/Form/TextFieldIcon/TextFieldIcon.styled.ts
packages/styled-components/src/components/primitives/Form/TextFieldIcon/TextFieldIcon.test.tsx
packages/styled-components/src/components/primitives/Form/TextFieldIcon/TextFieldIcon.tsx
packages/styled-components/src/components/primitives/Form/TextFieldIcon/TextFieldIcon.types.ts
packages/styled-components/src/components/primitives/Form/TextFieldIconButton/TextFieldIconButton.stories.tsx
packages/styled-components/src/components/primitives/Form/TextFieldIconButton/TextFieldIconButton.styled.ts
packages/styled-components/src/components/primitives/Form/TextFieldIconButton/TextFieldIconButton.test.tsx
packages/styled-components/src/components/primitives/Form/TextFieldIconButton/TextFieldIconButton.tsx
packages/styled-components/src/components/primitives/Form/TextFieldIconButton/TextFieldIconButton.types.ts
packages/styled-components/src/components/primitives/Form/TextFieldIconButton/index.tsx
packages/styled-components/src/components/primitives/index.ts

**Checklist**
https://trello.com/c/95Nr1LgN/94-migrate-composer-forms-to-styled-components

Styled TextFieldIconButton

---

.changeset/chilly-schools-poke.md
packages/contentful-core/package.json
packages/contentful-core/src/components/ComponentRenderer/ComponentRenderer.test.tsx
packages/contentful-core/src/context/ContentfulProvider.test.tsx
packages/contentful-core/src/renderers/renderFromContentfulModel.test.tsx
packages/contentful-core/src/renderers/renderFromContentfulModel.tsx

* add warnings to `renderFromContentfulModel` to prevent apps from breaking due to missing data
**Checklist**

update: Safeguard component rendering

---

.changeset/flat-parrots-relate.md
packages/components/package.json
packages/components/src/theme/ComposerTheme/Components/Select.ts

The postinstall script was making the package installation to fail, temporary remove it until we found a proper way to do it

Remove postinstall

---

.changeset/afraid-ties-boil.md
packages/components/src/components/primitives/Breadcrumb/types.ts
packages/components/src/components/primitives/Icons/types.ts
packages/components/src/components/primitives/Link/Link.stories.tsx
packages/components/src/components/primitives/Link/Link.test.tsx
packages/components/src/components/primitives/Link/Link.tsx
packages/components/src/components/primitives/Link/types.ts

**Checklist**
- https://impulsumvc.atlassian.net/browse/COM-393
- https://impulsumvc.atlassian.net/browse/COM-379
We have replace the `icon` and `iconPosition` props by `leadingIcon` and `trailingIcon`
- Also fix the spacing between the text and the icons

[COM-393] Add support for leading and trailing icons to Link

---

.changeset/short-dryers-flash.md
packages/components/src/components/primitives/Icons/types.ts
packages/components/src/components/primitives/Link/Link.stories.tsx
packages/components/src/components/primitives/Link/Link.tsx

This was causing a warning when rendering the Link _wrapped_ by text as `div` should not be a child of `p`
**Checklist**

Remove link wrapper

---

.changeset/spotty-icons-thank.md
packages/contentful-core/src/index.ts

We need to expose this method to avoid importing it from the full route

Expose create contentful link in contentful-core

---

.changeset/ten-jokes-dance.md
package.json
packages/nextjs-contentful-renderer/client/package.json

Reverts cmpsr/composer#523
After moving to this the @cmpsr/nextjs-contentful-renderer is no longer being published with the following error
:butterfly:  info Publishing “@cmpsr/nextjs-contentful-renderer” at “14.4.3"
:butterfly:  error an error occurred while publishing @cmpsr/nextjs-contentful-renderer: E402 402 Payment Required - PUT https://registry.npmjs.org/@cmpsr%2fnextjs-contentful-renderer - You must sign up for private packages
:butterfly:  error <Buffer 6e 70 6d 20 6e 6f 74 69 63 65 20 50 75 62 6c 69 73 68 69 6e 67 20 74 6f 20 68 74 74 70 73 3a 2f 2f 72 65 67 69 73 74 72 79 2e 6e 70 6d 6a 73 2e 6f 72 ... 495 more bytes>
Reverting this until we can go deeper in what's going on.

Revert "COM-543: Replace lerna publish command with changeset command"

---

.changeset/cold-pets-kiss.md
packages/blocks/src/HighlightedText/HighlightedText.tsx

Adding `display:flex` to `HighlightedText.Overline` so we can `alignSelf` the static member
**What is the ticket / issue associated with this change?** 
https://impulsumvc.atlassian.net/browse/COM-902

[COM-902] Add display flex to HighlightedText Overline

---

.changeset/spicy-paws-rush.md
packages/blocks/src/BrandLogos/BrandLogos.stories.tsx
packages/blocks/src/BrandLogos/BrandLogos.test.tsx
packages/blocks/src/BrandLogos/BrandLogos.tsx
packages/blocks/src/BrandLogos/types.ts

- Add support for `Overline` in `BrandLogos` block
- Replace `BrandLogos gap` for `marginBottom` to match design
**Checklist**
https://impulsumvc.atlassian.net/browse/COM-914

[COM-914] Add support for Overline in BrandLogos block

---

packages/components/src/components/other/Card/Card.stories.tsx

**Checklist**
Storybook is broken due to an invalid sb title

fix: remove invalid storybook title with double slash

---

.github/workflows/delete_storybook.yml

**Checklist**
Looks like it missing permissions to be able to authenticate with google cloud

COM-1167 Adds permissions to delete storybook github action

---

.changeset/brown-pants-pull.md
packages/nextjs-contentful-renderer/src/utils/getApolloClient/getApolloClient.ts

**Checklist**
Resolves an issue if the `CONTENTFUL_ENVIRONMENT` is not set in the `.env` it will properly default to `master`.

Add missing `CONTENTFUL_ENVIRONMENT` default

---

.changeset/stupid-dingos-rescue.md
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.test.ts
packages/cml/src/replaceCmlPlaceholders/replaceCmlPlaceholders.ts
packages/cml/src/types.ts

This PR enhances the handling of boolean and number field types by updating them to default to undefined when both the value and defaultValue are undefined.
**Checklist**

Refactor Boolean and Number Field Types to Default to Undefined

---

.changeset/silly-peas-wink.md
packages/components/src/components/navigation/Link/Link.stories.tsx
packages/components/src/components/navigation/Link/Link.test.tsx
packages/components/src/components/navigation/Link/Link.tsx
packages/components/src/components/navigation/Link/types.ts
packages/components/src/theme/ComposerTheme/Components/Link.ts

This pull request introduces the isInline property to the Link component. The addition of this property addresses a specific need for improved text wrapping behavior in scenarios where a link is embedded within a block of text.
**Background:**
Previously, our Link component faced challenges in handling long link texts within confined spaces, especially when the link was part of a larger text block. The standard inline-flex display didn't provide the flexibility needed for text wrapping, resulting in layout issues.
**Checklist**
https://impulsumvc.atlassian.net/browse/COM-1442

[COM-1442] Add new isInline property to Link component

---

.changeset/smart-roses-fly.md
packages/components/src/components/form/Checkbox/Checkbox.tsx

Resolved test environment warnings caused by media query attributes in the `Checkbox` component's responsive styles. Adjusted the `__css` prop handling to prevent invalid attribute names and ensure consistent rendering across environments.
**Checklist**

Resolve Test Warnings for Responsive Checkbox Styles
